<template>
  <view class="page">
    <view class="nav"><text class="nav-back" @click="goBack">←</text><text class="nav-title">好友申请</text><view style="width:48rpx"/></view>
    <view class="tab-row"><text class="tab" :class="{act:tab==='pending'}" @click="tab='pending'">待处理{{pendingCount}}</text><text class="tab" :class="{act:tab==='processed'}" @click="tab='processed'">已处理</text></view>
    <scroll-view scroll-y class="content" :style="{height:'calc(100vh - 56px - 56px)'}">
      <view v-for="r in list" :key="r.id" class="req-card">
        <text class="rc-avatar">{{r.user.name[0]}}</text><view class="rc-info"><text class="rc-name">{{r.user.name}}</text><text class="rc-reason">{{r.reason}}</text><text class="rc-time">{{r.time}}</text></view>
        <view v-if="tab==='pending'" class="rc-actions"><view class="rca-accept" @click="accept(r.id)">✓</view><view class="rca-reject" @click="reject(r.id)">✕</view></view>
        <text v-else class="rc-status" :class="r.status==='accepted'?'ok':'no'">{{r.status==='accepted'?'已通过':'已拒绝'}}</text>
      </view>
      <view v-if="list.length===0" class="empty"><text>暂无申请</text></view>
      <view style="height:48rpx"/>
    </scroll-view>
  </view>
</template>
<script setup lang="ts">import {ref,computed} from 'vue';import {onPullDownRefresh} from '@dcloudio/uni-app';const tab=ref<'pending'|'processed'>('pending');const requests=ref([{id:1,user:{name:'命理爱好者'},reason:'你好，想跟你请教八字问题',time:'2小时前',status:'pending'},{id:2,user:{name:'风水新手'},reason:'从群里加的你',time:'1天前',status:'pending'},{id:3,user:{name:'李易安'},reason:'名片推荐',time:'3天前',status:'accepted'}]);const pendingCount=computed(()=>requests.value.filter(r=>r.status==='pending').length);const list=computed(()=>requests.value.filter(r=>tab.value==='pending'?r.status==='pending':r.status!=='pending'));function accept(id:number){const r=requests.value.find(x=>x.id===id);if(r)r.status='accepted'};function reject(id:number){const r=requests.value.find(x=>x.id===id);if(r)r.status='rejected'};function goBack(){uni.navigateBack()};onPullDownRefresh(()=>setTimeout(()=>uni.stopPullDownRefresh(),500))</script>
<style scoped>.page{background:#FAF8F5;min-height:100vh}.nav{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:56px;background:#fff;border-bottom:1px solid #E8E0D5}.nav-back{font-size:36rpx;color:#2C2C2C}.nav-title{font-size:32rpx;font-weight:600}.tab-row{display:flex;gap:32rpx;padding:0 24rpx;height:56px;align-items:center;background:#FAF8F5;border-bottom:1px solid #E8E0D5}.tab{font-size:26rpx;color:#999;position:relative}.tab.act{color:#C41E3A;font-weight:500}.tab.act::after{content:'';position:absolute;bottom:-16rpx;left:0;right:0;height:4rpx;background:#C41E3A;border-radius:2rpx}.content{padding:24rpx}.req-card{display:flex;align-items:center;gap:16rpx;background:#fff;border-radius:20rpx;padding:24rpx;margin-bottom:12rpx;box-shadow:0 2rpx 12rpx rgba(0,0,0,.04)}.rc-avatar{width:80rpx;height:80rpx;border-radius:50%;background:#F5F1EB;display:flex;align-items:center;justify-content:center;font-size:30rpx;color:#2C2C2C;flex-shrink:0}.rc-info{flex:1}.rc-name{font-size:28rpx;font-weight:500;color:#2C2C2C;display:block}.rc-reason{font-size:24rpx;color:#999;margin-top:4rpx}.rc-time{font-size:20rpx;color:#ccc;margin-top:4rpx}.rc-actions{display:flex;gap:12rpx;flex-shrink:0}.rca-accept{width:64rpx;height:64rpx;border-radius:50%;background:#C41E3A;color:#fff;display:flex;align-items:center;justify-content:center;font-size:28rpx}.rca-reject{width:64rpx;height:64rpx;border-radius:50%;background:#F5F1EB;color:#999;display:flex;align-items:center;justify-content:center;font-size:28rpx}.rc-status{font-size:22rpx;padding:8rpx 16rpx;border-radius:12rpx}.rc-status.ok{background:rgba(34,197,94,.1);color:#22c55e}.rc-status.no{background:#F5F1EB;color:#999}.empty{padding:120rpx 0;text-align:center;font-size:26rpx;color:#999}
</style>
