<template>
  <view class="page"><view class="nav"><text class="nb" @click="goBack">←</text><text class="nt">{{step==='form'?'申请售后':'售后详情'}}</text><view style="width:48rpx"/></view>
    <scroll-view v-if="step==='form'" scroll-y class="c">
      <view class="card"><text class="ct">售后商品</text><view class="pr"><view class="pc">🛍️</view><view><text class="pn">{{orderProduct.name}}</text><text class="ps">{{orderProduct.spec}}·¥{{orderProduct.price}}</text></view></view></view>
      <view class="card"><text class="ct">售后类型</text><view class="tg"><text v-for="t in types" :key="t.id" class="ti" :class="{s:selType===t.id}" @click="selType=t.id"><text class="tii">{{t.icon}}</text><view><text class="tin">{{t.label}}</text><text class="tid">{{t.desc}}</text></view></text></view></view>
      <view class="card"><text class="ct">售后原因</text><view class="rg"><text v-for="r in reasons" :key="r.id" class="ri" :class="{s:selReason===r.id}" @click="selReason=r.id">{{r.label}}</text></view></view>
      <view class="card"><text class="ct">问题描述</text><textarea class="fi" placeholder="请详细描述问题..." :rows="3"/></view>
      <view class="card"><text class="ct">上传凭证(最多3张)</text><view class="up" @click="addImg">📷 上传图片</view></view>
      <view class="btn" @click="submit">提交申请</view><view style="height:48rpx"/></scroll-view>
    <scroll-view v-else scroll-y class="c"><view class="tl"><view v-for="s in steps" :key="s.id" class="tli"><view class="tic" :class="{d:s.status==='completed',a:s.status==='current'}"><text>{{s.status==='completed'?'✓':'●'}}</text></view><view><text class="tid">{{s.label}}</text><text v-if="s.time" class="tit">{{s.time}}</text></view></view></view></scroll-view></view>
</template>
<script setup lang="ts">import {ref} from 'vue';const step=ref('form'),selType=ref(''),selReason=ref('');const orderProduct={name:'渊海子平精装版',spec:'精装版',price:168};const types=[{id:'refund',label:'仅退款',desc:'无需退货',icon:'💳'},{id:'return',label:'退货退款',desc:'需寄回商品',icon:'📦'},{id:'exchange',label:'换货',desc:'申请换货',icon:'🚚'}];const reasons=[{id:'quality',label:'质量问题'},{id:'mismatch',label:'与描述不符'},{id:'wrong',label:'发错货'},{id:'unwanted',label:'不想要了'},{id:'other',label:'其他'}];const steps=[{id:1,label:'提交申请',status:'completed',time:'2024-05-09 14:30'},{id:2,label:'商家审核',status:'current',time:''},{id:3,label:'退货地址',status:'pending',time:''},{id:4,label:'用户寄回',status:'pending',time:''},{id:5,label:'商家收货',status:'pending',time:''},{id:6,label:'退款到账',status:'pending',time:''}];function addImg(){};function submit(){step.value='tracking'};function goBack(){uni.navigateBack()}</script>
<style scoped>.page{background:#FAF8F5;min-height:100vh}.nav{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:56px;background:#fff;border-bottom:1px solid #E8E0D5}.nb{font-size:36rpx;color:#2C2C2C}.nt{font-size:32rpx;font-weight:600}.c{padding:24rpx}.card{background:#fff;border-radius:16rpx;padding:24rpx;margin-bottom:16rpx;box-shadow:0 2rpx 8rpx rgba(0,0,0,.03)}.ct{font-size:26rpx;font-weight:600;color:#2C2C2C;margin-bottom:16rpx;display:block}.pr{display:flex;gap:16rpx;align-items:center}.pc{width:88rpx;height:88rpx;border-radius:12rpx;background:#F5F1EB;display:flex;align-items:center;justify-content:center;font-size:40rpx}.pn{font-size:26rpx;color:#2C2C2C;display:block}.ps{font-size:22rpx;color:#999}.tg{display:flex;flex-direction:column;gap:12rpx}.ti{display:flex;align-items:center;gap:16rpx;padding:20rpx;border:2rpx solid #E8E0D5;border-radius:16rpx}.ti.s{border-color:#C41E3A;background:rgba(196,30,58,.03)}.tii{font-size:32rpx}.tin{font-size:26rpx;font-weight:500;color:#2C2C2C;display:block}.tid{font-size:22rpx;color:#999}.rg{display:flex;flex-wrap:wrap;gap:12rpx}.ri{padding:14rpx 28rpx;background:#F5F1EB;border-radius:40rpx;font-size:24rpx;color:#999}.ri.s{background:#C41E3A;color:#fff}.fi{width:100%;padding:16rpx;background:#F5F1EB;border-radius:12rpx;font-size:24rpx;box-sizing:border-box;resize:none}.up{height:160rpx;border:2rpx dashed #E8E0D5;border-radius:12rpx;display:flex;align-items:center;justify-content:center;font-size:24rpx;color:#999}.btn{padding:28rpx;text-align:center;background:linear-gradient(90deg,#C41E3A,#E74C3C);color:#fff;border-radius:24rpx;font-size:28rpx;font-weight:600}.tl{padding:0 8rpx}.tli{display:flex;gap:16rpx;padding:16rpx 0}.tic{font-size:24rpx;width:36rpx;text-align:center}.tic.d{color:#22c55e}.tic.a{color:#C41E3A}.tic{color:#ccc}.tid{font-size:26rpx;color:#2C2C2C;display:block}.tit{font-size:20rpx;color:#999}
</style>
