module.exports = {
  apps: [
    {
      name: "guoxue-api",
      script: "scripts/pm2-api.js",
      cwd: "C:/Users/Administrator/Desktop/guoxue-platform",
      env: {
        NODE_ENV: "development",
        DATABASE_URL: "postgresql://guoxue:guoxue123@localhost:5433/guoxue",
        REDIS_URL: "redis://localhost:6379",
        JWT_SECRET: "dev-jwt-secret-for-local-testing-only-change-in-prod",
        ENCRYPTION_KEY: "0123456789abcdef0123456789abcdef",
        BIGSCREEN_SECRET: "dev-bigscreen-secret",
        BULLMQ_DISABLED: "true",
      },
      watch: false,
      max_memory_restart: "2G",
      error_file: "C:/Users/Administrator/Desktop/guoxue-platform/.pm2-logs/api-error.log",
      out_file: "C:/Users/Administrator/Desktop/guoxue-platform/.pm2-logs/api-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 10000,
    },
    {
      name: "guoxue-nginx",
      script: "C:/nginx/nginx.exe",
      args: "-p C:/nginx",
      cwd: "C:/nginx",
      env: {
        NODE_ENV: "production",
      },
      watch: false,
      max_memory_restart: "500M",
      error_file: "C:/Users/Administrator/Desktop/guoxue-platform/.pm2-logs/nginx-error.log",
      out_file: "C:/Users/Administrator/Desktop/guoxue-platform/.pm2-logs/nginx-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      kill_timeout: 5000,
    },
  ],
};
