<template>
  <view class="page"><view class="nav"><text class="nb" @click="goBack">←</text><text class="nt">优惠券</text><text class="ng" @click="goGet">领券中心</text></view>
    <view class="tb"><text v-for="t in tabs" :key="t.k" class="t" :class="{a:tab===t.k}" @click="tab=t.k">{{t.v}}</text></view>
    <scroll-view scroll-y class="c"><view v-for="c in list" :key="c.id" class="cp" :class="{u:c.used}">
      <view class="cpl"><text class="cv">¥{{c.v}}</text><text class="cn">{{c.n}}</text><text class="cc">{{c.cond}}</text></view><view class="cpr"><text class="cps">{{c.scope}}</text><text class="cpd">{{c.exp}}到期</text></view></view>
      <view v-if="list.length===0" class="e">暂无</view><view style="height:48rpx"/></scroll-view></view>
</template>
<script setup lang="ts">import {ref,computed} from 'vue';const tab=ref('unused');const tabs=[{k:'unused',v:'未使用'},{k:'used',v:'已使用'}];const coupons=ref([{id:1,v:50,n:'新人券',cond:'满299',scope:'全部课程',exp:'2024.12.31',used:false},{id:2,v:20,n:'满减券',cond:'满99',scope:'全部商品',exp:'2024.06.30',used:true}]);const list=computed(()=>tab.value==='unused'?coupons.value.filter((c:any)=>!c.used):coupons.value.filter((c:any)=>c.used));function goGet(){uni.navigateTo({url:'/pages/coupons/center/index'})};function goBack(){uni.navigateBack()}</script>
<style scoped>.page{background:#FAF8F5;min-height:100vh}.nav{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:56px;background:#fff;border-bottom:1px solid #E8E0D5}.nb{font-size:36rpx;color:#2C2C2C}.nt{font-size:32rpx;font-weight:600}.ng{font-size:24rpx;color:#C41E3A}.tb{display:flex;gap:32rpx;padding:16rpx 24rpx}.t{font-size:24rpx;color:#999;position:relative}.t.a{color:#C41E3A;font-weight:500}.t.a::after{content:'';position:absolute;bottom:-16rpx;left:0;right:0;height:4rpx;background:#C41E3A;border-radius:2rpx}.c{padding:24rpx}.cp{display:flex;background:linear-gradient(90deg,#C41E3A,#C41E3A);border-radius:16rpx;overflow:hidden;margin-bottom:16rpx}.cp.u{opacity:.5}.cpl{width:200rpx;display:flex;flex-direction:column;align-items:center;justify-content:center;color:#fff;padding:24rpx}.cv{font-size:48rpx;font-weight:700}.cn{font-size:22rpx;opacity:.8}.cc{font-size:18rpx;opacity:.7}.cpr{flex:1;background:#fff;border-radius:0 16rpx 16rpx 0;padding:24rpx}.cps{font-size:26rpx;font-weight:500;color:#2C2C2C;display:block}.cpd{font-size:20rpx;color:#999;margin-top:8rpx}.e{padding:160rpx 0;text-align:center;font-size:26rpx;color:#999}
</style>
