/**
 * 易经工具全集 — 中央注册表
 *
 * 所有 32 个工具的元信息、分类、输入schema定义。
 * 前端首页目录和后端路由均以此为准。
 */

import type { ToolEntry, ToolCategoryGroup } from "../types/tools/tool-registry";

// ── 分类定义 ──

export const CATEGORY_LABELS: Record<string, { label: string; icon: string }> = {
  "bazi-ziwei": { label: "八字紫微", icon: "calendar" },
  "qimen":       { label: "奇门遁甲", icon: "compass" },
  "liuren":      { label: "六壬神课", icon: "droplet" },
  "divination":  { label: "占卜", icon: "hexagram" },
  "fengshui":    { label: "风水", icon: "mountain" },
  "xingming":    { label: "星命", icon: "star" },
  "naming":      { label: "起名", icon: "edit" },
  "utility":     { label: "工具字典", icon: "wrench" },
};

// ── 全部工具注册 ──

export const ALL_TOOLS: ToolEntry[] = [
  // ═══════════════ 八字紫微 ═══════════════
  {
    id: "bazi",
    name: "八字排盘",
    subtitle: "四柱命理·人生密码",
    category: "bazi-ziwei",
    icon: "bazi",
    route: "/tools/bazi",
    visible: true,
    sortOrder: 1,
    inputSchema: {
      type: "object",
      properties: {
        name:    { type: "string", label: "姓名" },
        gender:  { type: "enum", label: "性别", values: ["男", "女"] },
        year:    { type: "number", label: "出生年", min: 1900, max: 2100 },
        month:   { type: "number", label: "出生月", min: 1, max: 12 },
        day:     { type: "number", label: "出生日", min: 1, max: 31 },
        hour:    { type: "number", label: "出生时", min: 0, max: 23 },
        minute:  { type: "number", label: "出生分", min: 0, max: 59, required: false },
        city:    { type: "string", label: "出生城市", required: false },
        trueSolar: { type: "boolean", label: "真太阳时", default: false },
        ziShiMode: { type: "enum", label: "早晚子时", values: ["traditional", "early-late"], default: "traditional" },
        daylightSaving: { type: "boolean", label: "夏令时", default: false },
      },
      required: ["gender", "year", "month", "day", "hour"],
    },
    requireAuth: false,
    status: "active",
    description: "四柱八字排盘，含藏干、纳音、神煞、大运流年、AI命理分析",
  },
  {
    id: "ziwei",
    name: "紫微斗数",
    subtitle: "十二宫·星曜命盘",
    category: "bazi-ziwei",
    icon: "ziwei",
    route: "/tools/ziwei",
    visible: true,
    sortOrder: 2,
    inputSchema: {
      type: "object",
      properties: {
        name:    { type: "string", label: "姓名" },
        gender:  { type: "enum", label: "性别", values: ["男", "女"] },
        year:    { type: "number", label: "出生年", min: 1900, max: 2100 },
        month:   { type: "number", label: "出生月", min: 1, max: 12 },
        day:     { type: "number", label: "出生日", min: 1, max: 31 },
        hour:    { type: "number", label: "出生时", min: 0, max: 23 },
        trueSolar: { type: "boolean", label: "真太阳时", default: false },
        daylightSaving: { type: "boolean", label: "夏令时", default: false },
        runYueMode: { type: "enum", label: "闰月分界", values: ["as-current", "as-next", "mid-month"], default: "as-next" },
        changShengMode: { type: "enum", label: "长生顺逆", values: ["all-shun", "by-year-gan", "by-gender"], default: "by-year-gan" },
      },
      required: ["gender", "year", "month", "day", "hour"],
    },
    requireAuth: false,
    status: "active",
    description: "紫微斗数命盘，支持三合/飞星/四化多流派，文墨天机兼容",
  },
  {
    id: "chenggu",
    name: "称骨算命",
    subtitle: "袁天罡·骨重论命",
    category: "bazi-ziwei",
    icon: "scale",
    route: "/tools/chenggu",
    visible: true,
    sortOrder: 2.5,
    inputSchema: {
      type: "object",
      properties: {
        year:    { type: "number", label: "出生年", min: 1900, max: 2100 },
        month:   { type: "number", label: "出生月", min: 1, max: 12 },
        day:     { type: "number", label: "出生日", min: 1, max: 31 },
        hour:    { type: "number", label: "出生时", min: 0, max: 23 },
        gender:  { type: "enum", label: "性别", values: ["男", "女"], required: false },
      },
      required: ["year", "month", "day", "hour"],
    },
    requireAuth: false,
    status: "active",
    description: "袁天罡称骨算命，年月日时四柱骨重相加，对应称骨歌诀论命",
  },
  {
    id: "bazi-hehun",
    name: "八字合婚",
    subtitle: "双人命盘·姻缘匹配",
    category: "bazi-ziwei",
    icon: "heart",
    route: "/tools/bazi-hehun",
    visible: true,
    sortOrder: 2.6,
    inputSchema: {
      type: "object",
      properties: {
        male: { type: "object", label: "男方", properties: {
          year:  { type: "number", label: "出生年", min: 1900, max: 2100 },
          month: { type: "number", label: "出生月", min: 1, max: 12 },
          day:   { type: "number", label: "出生日", min: 1, max: 31 },
          hour:  { type: "number", label: "出生时", min: 0, max: 23 },
        } },
        female: { type: "object", label: "女方", properties: {
          year:  { type: "number", label: "出生年", min: 1900, max: 2100 },
          month: { type: "number", label: "出生月", min: 1, max: 12 },
          day:   { type: "number", label: "出生日", min: 1, max: 31 },
          hour:  { type: "number", label: "出生时", min: 0, max: 23 },
        } },
      },
      required: ["male", "female"],
    },
    requireAuth: false,
    status: "active",
    description: "八字合婚，双人排盘综合分析生肖/日柱/五行/十神/用神五维匹配度",
  },

  // ═══════════════ 占卜 — 灵签 ═══════════════
  {
    id: "lingqian",
    name: "观音灵签",
    subtitle: "百签问卦·诚心求解",
    category: "divination",
    icon: "scroll",
    route: "/tools/lingqian",
    visible: true,
    sortOrder: 25,
    inputSchema: {
      type: "object",
      properties: {
        type:     { type: "enum", label: "签种", values: ["guanyin", "guandi", "lvzu", "mazu", "huangdaxian", "yuelao"], default: "guanyin" },
        question: { type: "string", label: "所问事项", required: false },
        seed:     { type: "number", label: "报数", required: false },
      },
      required: [],
    },
    requireAuth: false,
    status: "active",
    description: "观音灵签100签，诚心摇签求解事业/财运/姻缘/健康",
  },
  {
    id: "shengxiao-yunshi",
    name: "生肖运势",
    subtitle: "十二生肖·每日运程",
    category: "divination",
    icon: "zodiac",
    route: "/tools/shengxiao-yunshi",
    visible: true,
    sortOrder: 26,
    inputSchema: {
      type: "object",
      properties: {
        shengXiao: { type: "enum", label: "生肖", values: ["鼠", "牛", "虎", "兔", "龙", "蛇", "马", "羊", "猴", "鸡", "狗", "猪"] },
        birthYear: { type: "number", label: "出生年", required: false, min: 1924, max: 2100 },
        date:      { type: "string", label: "查询日期", required: false },
      },
      required: [],
    },
    requireAuth: false,
    status: "active",
    description: "十二生肖每日运势，含太岁关系/五维评分/幸运色/方位/宜忌",
  },
  {
    id: "xingzuo-yunshi",
    name: "星座运势",
    subtitle: "十二星座·每日运程",
    category: "divination",
    icon: "star",
    route: "/tools/xingzuo-yunshi",
    visible: true,
    sortOrder: 27,
    inputSchema: {
      type: "object",
      properties: {
        xingZuo:    { type: "enum", label: "星座", values: ["白羊座", "金牛座", "双子座", "巨蟹座", "狮子座", "处女座", "天秤座", "天蝎座", "射手座", "摩羯座", "水瓶座", "双鱼座"] },
        birthMonth: { type: "number", label: "出生月", required: false, min: 1, max: 12 },
        birthDay:   { type: "number", label: "出生日", required: false, min: 1, max: 31 },
        date:       { type: "string", label: "查询日期", required: false },
      },
      required: [],
    },
    requireAuth: false,
    status: "active",
    description: "十二星座每日运势，含元素属性/五维评分/幸运色/配对星座/建议",
  },
  {
    id: "jiemeng",
    name: "周公解梦",
    subtitle: "梦境解析·吉凶预示",
    category: "divination",
    icon: "dream",
    route: "/tools/jiemeng",
    visible: true,
    sortOrder: 28,
    inputSchema: {
      type: "object",
      properties: {
        dream: { type: "string", label: "梦境描述", desc: "请输入您梦到的内容，如「梦到蛇」「梦见大水」等" },
      },
      required: ["dream"],
    },
    requireAuth: false,
    status: "active",
    description: "周公解梦经典梦典，涵盖130+梦境条目，关键词匹配+吉凶解读",
  },
  {
    id: "huangli",
    name: "每日黄历",
    subtitle: "宜忌吉凶·每日速查",
    category: "utility",
    icon: "calendar",
    route: "/tools/huangli",
    visible: true,
    sortOrder: 60,
    inputSchema: {
      type: "object",
      properties: {
        date: { type: "string", label: "日期", required: false },
      },
      required: [],
    },
    requireAuth: false,
    status: "active",
    description: "每日黄历速查，含宜忌/冲煞/财神方位/吉神凶煞/吉时/节气",
  },
  {
    id: "yizhangjing",
    name: "达摩一掌经",
    subtitle: "六道轮回·掌中论命",
    category: "bazi-ziwei",
    icon: "palm",
    route: "/tools/yizhangjing",
    visible: true,
    sortOrder: 2.7,
    inputSchema: {
      type: "object",
      properties: {
        year:  { type: "number", label: "出生年", min: 1900, max: 2100 },
        month: { type: "number", label: "出生月", min: 1, max: 12 },
        day:   { type: "number", label: "出生日", min: 1, max: 31 },
        hour:   { type: "number", label: "出生时", min: 0, max: 23 },
        gender: { type: "string", label: "性别", enum: ["男", "女"] },
      },
      required: ["year", "month", "day", "hour", "gender"],
    },
    requireAuth: false,
    status: "active",
    description: "达摩一掌经，十二宫配六道，男顺女逆推演，四柱六道轮回论命",
  },
  {
    id: "bazi-liuri",
    name: "八字流日流时",
    subtitle: "日时精推·趋吉避凶",
    category: "bazi-ziwei",
    icon: "calendar-clock",
    route: "/tools/bazi-liuri",
    visible: true,
    sortOrder: 2.8,
    inputSchema: {
      type: "object",
      properties: {
        year:        { type: "number", label: "出生年", min: 1900, max: 2100 },
        month:       { type: "number", label: "出生月", min: 1, max: 12 },
        day:         { type: "number", label: "出生日", min: 1, max: 31 },
        hour:        { type: "number", label: "出生时", min: 0, max: 23 },
        gender:      { type: "string", label: "性别", enum: ["男", "女"] },
        targetYear:  { type: "number", label: "查询年", min: 1900, max: 2100 },
        targetMonth: { type: "number", label: "查询月", min: 1, max: 12 },
        targetDay:   { type: "number", label: "查询日", min: 1, max: 31 },
        targetHour:  { type: "number", label: "查询时(可选)", min: 0, max: 23 },
      },
      required: ["year", "month", "day", "hour", "gender", "targetYear", "targetMonth", "targetDay"],
    },
    requireAuth: false,
    status: "active",
    description: "八字流日流时分析，结合本命四柱与目标日/时干支，推算当日运势、合冲刑害、吉凶提示",
  },
  {
    id: "ziwei-liuri",
    name: "紫微流日流时",
    subtitle: "星曜流转·日时精批",
    category: "bazi-ziwei",
    icon: "stars",
    route: "/tools/ziwei-liuri",
    visible: true,
    sortOrder: 2.9,
    inputSchema: {
      type: "object",
      properties: {
        year:        { type: "number", label: "出生年", min: 1900, max: 2100 },
        month:       { type: "number", label: "出生月", min: 1, max: 12 },
        day:         { type: "number", label: "出生日", min: 1, max: 31 },
        hour:        { type: "number", label: "出生时", min: 0, max: 23 },
        gender:      { type: "string", label: "性别", enum: ["男", "女"] },
        targetYear:  { type: "number", label: "查询年", min: 1900, max: 2100 },
        targetMonth: { type: "number", label: "查询月", min: 1, max: 12 },
        targetDay:   { type: "number", label: "查询日", min: 1, max: 31 },
        targetHour:  { type: "number", label: "查询时(可选)", min: 0, max: 23 },
      },
      required: ["year", "month", "day", "hour", "gender", "targetYear", "targetMonth", "targetDay"],
    },
    requireAuth: false,
    status: "active",
    description: "紫微斗数流日流时分析，命盘星曜与流日宫位交叉推演，四化飞星日运精批",
  },
  {
    id: "ziwei-hepan",
    name: "紫微合盘",
    subtitle: "双盘比对·命缘和合",
    category: "bazi-ziwei",
    icon: "users",
    route: "/tools/ziwei-hepan",
    visible: true,
    sortOrder: 2.85,
    inputSchema: {
      type: "object",
      properties: {
        "self.year":    { type: "number", label: "本人出生年", min: 1900, max: 2100 },
        "self.month":   { type: "number", label: "本人出生月", min: 1, max: 12 },
        "self.day":     { type: "number", label: "本人出生日", min: 1, max: 31 },
        "self.hour":    { type: "number", label: "本人出生时", min: 0, max: 23 },
        "self.gender":  { type: "string", label: "本人性别", enum: ["男", "女"] },
        "partner.year":   { type: "number", label: "对方出生年", min: 1900, max: 2100 },
        "partner.month":  { type: "number", label: "对方出生月", min: 1, max: 12 },
        "partner.day":    { type: "number", label: "对方出生日", min: 1, max: 31 },
        "partner.hour":   { type: "number", label: "对方出生时", min: 0, max: 23 },
        "partner.gender": { type: "string", label: "对方性别", enum: ["男", "女"] },
      },
      required: ["self.year", "self.month", "self.day", "self.hour", "self.gender", "partner.year", "partner.month", "partner.day", "partner.hour", "partner.gender"],
    },
    requireAuth: false,
    status: "active",
    description: "紫微合盘，双人紫微命盘对比，命宫/夫妻宫星曜配对、四化交飞、地支关系综合评分",
  },
  {
    id: "zeri",
    name: "择日大全",
    subtitle: "择吉避凶·百事合宜",
    category: "bazi-ziwei",
    icon: "calendar-check",
    route: "/tools/zeri",
    visible: true,
    sortOrder: 2.95,
    inputSchema: {
      type: "object",
      properties: {
        eventType:  { type: "string", label: "事项类型", enum: ["嫁娶", "搬家", "开业", "出行", "动土", "安床", "入宅", "上梁", "开光", "纳采", "祈福", "解除", "修造", "栽种", "交易", "安葬"] },
        startDate:  { type: "string", label: "开始日期", format: "date" },
        endDate:    { type: "string", label: "结束日期", format: "date" },
        maxResults: { type: "number", label: "最多返回条数", min: 1, max: 30 },
      },
      required: ["eventType", "startDate", "endDate"],
    },
    requireAuth: false,
    status: "active",
    description: "择日大全，综合黄历宜忌、建除十二直、二十八宿、天神吉凶，智能筛选吉日",
  },
  {
    id: "heluo",
    name: "河洛理数",
    subtitle: "数理命象·先后天卦",
    category: "bazi-ziwei",
    icon: "binary",
    route: "/tools/heluo",
    visible: true,
    sortOrder: 2.96,
    inputSchema: {
      type: "object",
      properties: {
        year:   { type: "number", label: "出生年", min: 1900, max: 2100 },
        month:  { type: "number", label: "出生月", min: 1, max: 12 },
        day:    { type: "number", label: "出生日", min: 1, max: 31 },
        hour:   { type: "number", label: "出生时", min: 0, max: 23 },
        gender: { type: "string", label: "性别", enum: ["男", "女"] },
      },
      required: ["year", "month", "day", "hour", "gender"],
    },
    requireAuth: false,
    status: "active",
    description: "河洛理数，以生辰八字转化河洛数值，推演六十四卦卦象与变卦，数理论命",
  },
  {
    id: "yanggong",
    name: "杨公风水",
    subtitle: "二十四山·零正神断",
    category: "fengshui",
    icon: "compass",
    route: "/tools/yanggong",
    visible: true,
    sortOrder: 5.1,
    inputSchema: {
      type: "object",
      properties: {
        sitting: { type: "string", label: "坐山", enum: ["壬","子","癸","丑","艮","寅","甲","卯","乙","辰","巽","巳","丙","午","丁","未","坤","申","庚","酉","辛","戌","乾","亥"] },
        period:  { type: "number", label: "元运(1-9)", min: 1, max: 9 },
      },
      required: ["sitting"],
    },
    requireAuth: false,
    status: "active",
    description: "杨公风水，二十四山向分析，三元九运零正神断法，城门诀，坐山旺衰判断",
  },
  {
    id: "jinsuo",
    name: "金锁玉关",
    subtitle: "过路阴阳·砂水定吉",
    category: "fengshui",
    icon: "lock",
    route: "/tools/jinsuo",
    visible: true,
    sortOrder: 5.2,
    inputSchema: {
      type: "object",
      properties: {
        kan:  { type: "string", label: "北方(坎)", enum: ["砂", "水", "未知"] },
        kun:  { type: "string", label: "西南(坤)", enum: ["砂", "水", "未知"] },
        zhen: { type: "string", label: "东方(震)", enum: ["砂", "水", "未知"] },
        xun:  { type: "string", label: "东南(巽)", enum: ["砂", "水", "未知"] },
        qian: { type: "string", label: "西北(乾)", enum: ["砂", "水", "未知"] },
        dui:  { type: "string", label: "西方(兑)", enum: ["砂", "水", "未知"] },
        gen:  { type: "string", label: "东北(艮)", enum: ["砂", "水", "未知"] },
        li:   { type: "string", label: "南方(离)", enum: ["砂", "水", "未知"] },
      },
      required: [],
    },
    requireAuth: false,
    status: "active",
    description: "金锁玉关(过路阴阳)，1234要砂6789要水，八方砂水定吉凶，简易实用风水断法",
  },

  // ═══════════════ 奇门遁甲 ═══════════════
  {
    id: "qimen-yang",
    name: "阳盘奇门",
    subtitle: "传统奇门·转盘飞盘",
    category: "qimen",
    icon: "qimen",
    route: "/tools/qimen-yang",
    visible: true,
    sortOrder: 3,
    inputSchema: {
      type: "object",
      properties: {
        datetime:   { type: "datetime", label: "排盘时间", default: "now" },
        method:     { type: "enum", label: "排盘方法", values: ["zhuanpan", "feipan"], default: "zhuanpan" },
        feiGongMode:{ type: "enum", label: "飞宫方式", values: ["yang-shun-yin-ni", "yinyang-jie-shun"], default: "yang-shun-yin-ni" },
        qiJuMethod: { type: "enum", label: "起居方式", values: ["chaibu", "maoshan", "zhirun", "zixuan"], default: "chaibu" },
        customJu:   { type: "number", label: "自选局", min: 1, max: 9, required: false },
        anGanMethod:{ type: "enum", label: "暗干起法", values: ["zhishimen-qi", "men-dipan-qi"], default: "zhishimen-qi" },
        trueSolar:  { type: "boolean", label: "真太阳时", default: false },
      },
      required: [],
    },
    requireAuth: false,
    status: "active",
    description: "阳盘奇门遁甲，支持转盘/飞盘、拆补/茅山/置润/自选定局",
  },
  {
    id: "qimen-yang-mingli",
    name: "阳盘命理奇门",
    subtitle: "奇门八字·命理解析",
    category: "qimen",
    icon: "mingli-qimen",
    route: "/tools/qimen-yang-mingli",
    visible: true,
    sortOrder: 4,
    inputSchema: {
      type: "object",
      properties: {
        birthTime:  { type: "datetime", label: "出生时间" },
        birthplace: { type: "string", label: "出生地点", required: false },
        gender:     { type: "enum", label: "性别", values: ["男", "女"] },
        jiGongMode: { type: "enum", label: "寄宫方式", values: ["kungong", "yang-gen-yin-kun"], default: "kungong" },
        trueSolar:  { type: "boolean", label: "真太阳时", default: false },
        ziShiMode:  { type: "enum", label: "早晚子时", values: ["traditional", "early-late"], default: "traditional" },
        daylightSaving: { type: "boolean", label: "夏令时", default: false },
      },
      required: ["birthTime", "gender"],
    },
    requireAuth: false,
    status: "active",
    description: "用奇门理论做八字命理分析，支持奇门⇄八字双盘切换",
  },
  {
    id: "qimen-yin",
    name: "阴盘奇门",
    subtitle: "王凤麟·移星换斗",
    category: "qimen",
    icon: "yin-qimen",
    route: "/tools/qimen-yin",
    visible: true,
    sortOrder: 5,
    inputSchema: {
      type: "object",
      properties: {
        datetime:   { type: "datetime", label: "排盘时间", default: "now" },
        panType:    { type: "enum", label: "排盘类型", values: ["nian", "ri", "shi", "ke"], default: "shi" },
        customJu:   { type: "number", label: "自选局", min: 1, max: 9, required: false },
        trueSolar:  { type: "boolean", label: "真太阳时", default: false },
      },
      required: [],
    },
    requireAuth: false,
    status: "active",
    description: "王凤麟阴盘遁甲，年/日/时/刻盘，支持移星换斗/天门地户/神将",
  },
  {
    id: "qimen-yin-mingli",
    name: "阴盘命理奇门",
    subtitle: "阴盘命理·大运流年",
    category: "qimen",
    icon: "yin-mingli-qimen",
    route: "/tools/qimen-yin-mingli",
    visible: true,
    sortOrder: 6,
    inputSchema: {
      type: "object",
      properties: {
        birthTime:  { type: "datetime", label: "出生时间" },
        birthplace: { type: "string", label: "出生地点", required: false },
        gender:     { type: "enum", label: "性别", values: ["男", "女"] },
        trueSolar:  { type: "boolean", label: "真太阳时", default: false },
        ziShiMode:  { type: "enum", label: "早晚子时", values: ["traditional", "early-late"], default: "traditional" },
        daylightSaving: { type: "boolean", label: "夏令时", default: false },
      },
      required: ["birthTime", "gender"],
    },
    requireAuth: false,
    status: "active",
    description: "阴盘奇门命理解析，叠加出生时间与大运流年",
  },
  {
    id: "shanxiang-qimen",
    name: "山向奇门",
    subtitle: "坐山朝向·风水择日",
    category: "qimen",
    icon: "mountain-compass",
    route: "/tools/shanxiang-qimen",
    visible: true,
    sortOrder: 7,
    inputSchema: {
      type: "object",
      properties: {
        zuoShan:   { type: "enum", label: "坐山", values: ["壬","子","癸","丑","艮","寅","甲","卯","乙","辰","巽","巳","丙","午","丁","未","坤","申","庚","酉","辛","戌","乾","亥"] },
        xiang:     { type: "enum", label: "朝向", values: ["壬","子","癸","丑","艮","寅","甲","卯","乙","辰","巽","巳","丙","午","丁","未","坤","申","庚","酉","辛","戌","乾","亥"] },
        duShu:     { type: "number", label: "度数（0-15）", min: 0, max: 15 },
        year:      { type: "number", label: "用事年份", min: 1900, max: 2100 },
      },
      required: ["zuoShan", "xiang", "duShu"],
    },
    requireAuth: false,
    status: "active",
    description: "24山72局定局，坐山朝向风水排盘",
  },
  {
    id: "qimen-chuanren",
    name: "奇门穿壬",
    subtitle: "奇门六壬·穿针引线",
    category: "qimen",
    icon: "chuanren",
    route: "/tools/qimen-chuanren",
    visible: true,
    sortOrder: 8,
    inputSchema: {
      type: "object",
      properties: {
        datetime:   { type: "datetime", label: "排盘时间", default: "now" },
        method:     { type: "enum", label: "排盘方法", values: ["zhuanpan", "feipan"], default: "zhuanpan" },
        qiJuMethod: { type: "enum", label: "起居方式", values: ["chaibu", "maoshan", "zhirun"], default: "chaibu" },
        trueSolar:  { type: "boolean", label: "真太阳时", default: false },
      },
      required: [],
    },
    requireAuth: false,
    status: "active",
    description: "内奇门外六壬双层嵌套，七十二局穿针引线",
  },
  {
    id: "qimen-fuzhou",
    name: "奇门符咒",
    subtitle: "移星换斗·符咒化解",
    category: "qimen",
    icon: "fuzhou",
    route: "/tools/qimen-fuzhou",
    visible: true,
    sortOrder: 9,
    inputSchema: {
      type: "object",
      properties: {
        datetime:    { type: "datetime", label: "排盘时间", default: "now" },
        target:      { type: "enum", label: "化解目标", values: ["财运","健康","感情","事业","学业","综合"], default: "综合" },
        description: { type: "string", label: "具体诉求", required: false },
      },
      required: ["datetime", "target"],
    },
    requireAuth: false,
    status: "active",
    description: "奇门符咒化解，转宫/拆填/添加三法，42种符咒+星门神组合",
  },
  {
    id: "qimen-acupuncture",
    name: "奇门针灸",
    subtitle: "九宫应窍·奇门针灸",
    category: "qimen",
    icon: "acupuncture",
    route: "/tools/qimen-acupuncture",
    visible: true,
    sortOrder: 10,
    inputSchema: {
      type: "object",
      properties: {
        datetime:        { type: "datetime", label: "排盘时间", default: "now" },
        chiefComplaint:  { type: "string", label: "主诉病症", required: false },
        targetBodyPart:  { type: "string", label: "主诉部位", required: false },
      },
      required: ["datetime"],
    },
    requireAuth: false,
    status: "active",
    description: "九宫应九窍，经络配穴，90条病机+30+部位穴位数据库",
  },

  // ═══════════════ 占卜 ═══════════════
  {
    id: "liuyao",
    name: "六爻",
    subtitle: "纳甲预测·铜钱起卦",
    category: "divination",
    icon: "liuyao",
    route: "/tools/liuyao",
    visible: true,
    sortOrder: 10,
    inputSchema: {
      type: "object",
      properties: {
        method:    { type: "enum", label: "起卦方式", values: ["time","manual","shake","hex-name","number-2","number-3","auto","phone","stroke"], default: "shake" },
        datetime:  { type: "datetime", label: "起卦时间", default: "now", required: false },
        numbers2:  { type: "array", label: "两个数字", required: false },
        numbers3:  { type: "array", label: "三个数字", required: false },
        hexName:   { type: "string", label: "卦名", required: false },
        dongYaoPositions: { type: "array", label: "动爻位置", required: false },
      },
      required: ["method"],
    },
    requireAuth: false,
    status: "active",
    description: "9种起卦方式，纳甲装卦，本卦变卦互卦完整解读",
  },
  {
    id: "meihua",
    name: "梅花易数",
    subtitle: "观物取象·体用生克",
    category: "divination",
    icon: "meihua",
    route: "/tools/meihua",
    visible: true,
    sortOrder: 11,
    inputSchema: {
      type: "object",
      properties: {
        method:    { type: "enum", label: "起卦方式", values: ["time","manual","number","auto"], default: "time" },
        datetime:  { type: "datetime", label: "起卦时间", default: "now", required: false },
        numbers:   { type: "array", label: "数字", required: false },
        upperGua:  { type: "number", label: "上卦", min: 1, max: 8, required: false },
        lowerGua:  { type: "number", label: "下卦", min: 1, max: 8, required: false },
        dongYao:   { type: "number", label: "动爻", min: 1, max: 6, required: false },
      },
      required: ["method"],
    },
    requireAuth: false,
    status: "active",
    description: "本卦变卦互卦，策轨元会运世，体用生克断语",
  },

  // ═══════════════ 六壬神课 ═══════════════
  {
    id: "daliuren",
    name: "大六壬",
    subtitle: "天盘四课·三传断事",
    category: "liuren",
    icon: "liuren",
    route: "/tools/daliuren",
    visible: true,
    sortOrder: 20,
    inputSchema: {
      type: "object",
      properties: {
        datetime:       { type: "datetime", label: "起课时间", default: "now" },
        birthYear:      { type: "number", label: "命主出生年", min: 1900, max: 2100 },
        gender:         { type: "enum", label: "性别", values: ["男", "女"] },
        liveTime:       { type: "datetime", label: "活时", default: "now" },
        reportNumber:   { type: "number", label: "报数", required: false, min: 1, max: 999 },
        random:         { type: "boolean", label: "随机起课", default: false },
        jiangMethod:    { type: "enum", label: "换将方式", values: ["zhongqi", "jiaojie"], default: "zhongqi" },
        guiRenJue:      { type: "enum", label: "贵人诀", values: ["jiawugeng-niuyang", "jiayang-wugengniu"], default: "jiawugeng-niuyang" },
        guiRenDayNight: { type: "enum", label: "贵神昼夜", values: ["maoyou", "day", "night"], default: "maoyou" },
        sheHaiType:     { type: "enum", label: "涉害取法", values: ["mengzhongji", "shenqian"], default: "mengzhongji" },
        trueSolar:      { type: "boolean", label: "真太阳时", default: false },
      },
      required: ["datetime", "birthYear", "gender", "liveTime"],
    },
    requireAuth: false,
    status: "active",
    description: "天地盘+四课+三传，九宗门，十二天将，64课经+毕法赋",
  },
  {
    id: "xiaoliuren",
    name: "小六壬",
    subtitle: "掌诀推算·简单直观",
    category: "liuren",
    icon: "xiaoliuren",
    route: "/tools/xiaoliuren",
    visible: true,
    sortOrder: 21,
    inputSchema: {
      type: "object",
      properties: {
        datetime:     { type: "datetime", label: "排盘时间", default: "now" },
        type:         { type: "enum", label: "排盘类型", values: ["daojia", "jiangshi", "jiangshi2"], default: "daojia" },
        method:       { type: "enum", label: "起课方式", values: ["time", "baoshu"], default: "time" },
        reportNumber: { type: "number", label: "报数", required: false, min: 1, max: 99999 },
      },
      required: ["datetime", "type", "method"],
    },
    requireAuth: false,
    status: "active",
    description: "掌诀推算，大安/留连/速喜/赤口/小吉/空亡六宫，支持道家/江式/江式2三派",
  },
  {
    id: "jinkoujue",
    name: "金口诀",
    subtitle: "四位直断·占验如神",
    category: "liuren",
    icon: "jinkoujue",
    route: "/tools/jinkoujue",
    visible: true,
    sortOrder: 22,
    inputSchema: {
      type: "object",
      properties: {
        datetime:       { type: "datetime", label: "排盘时间", default: "now" },
        diFen:          { type: "enum", label: "地分", values: ["子","丑","寅","卯","辰","巳","午","未","申","酉","戌","亥"], default: "子" },
        diFenMethod:    { type: "enum", label: "地分方式", values: ["select", "baoshu", "random"], default: "select" },
        jiangMethod:    { type: "enum", label: "换将方式", values: ["zhongqi", "jiaojie"], default: "zhongqi" },
        guiRenJue:      { type: "enum", label: "贵人诀", values: ["jiawugeng-niuyang", "jiayang-wugengniu"], default: "jiawugeng-niuyang" },
        guiRenDayNight: { type: "enum", label: "贵神昼夜", values: ["maoyou", "day", "night"], default: "maoyou" },
        trueSolar:      { type: "boolean", label: "真太阳时", default: false },
      },
      required: ["datetime", "diFen", "diFenMethod"],
    },
    requireAuth: false,
    status: "active",
    description: "大六壬简化·四位直断，人元/贵神/月将/地分，五动三动断课",
    /** 关联工具切换 */
    crossTools: ["qimen-yin", "qimen-chuanren"],
  },

  // ═══════════════ 风水 ═══════════════
  {
    id: "xuankong-feixing",
    name: "玄空飞星",
    subtitle: "九宫飞星·三元九运",
    category: "fengshui",
    icon: "feixing",
    route: "/tools/xuankong-feixing",
    visible: true,
    sortOrder: 30,
    inputSchema: {
      type: "object",
      properties: {
        shan:     { type: "enum", label: "坐山", values: ["壬","子","癸","丑","艮","寅","甲","卯","乙","辰","巽","巳","丙","午","丁","未","坤","申","庚","酉","辛","戌","乾","亥"] },
        xiang:    { type: "enum", label: "朝向", values: ["壬","子","癸","丑","艮","寅","甲","卯","乙","辰","巽","巳","丙","午","丁","未","坤","申","庚","酉","辛","戌","乾","亥"] },
        year:     { type: "number", label: "建造年份", min: 1900, max: 2100 },
        yuanYun:  { type: "number", label: "元运", min: 1, max: 9, required: false },
        tiGua:    { type: "boolean", label: "考虑替卦", default: true },
      },
      required: ["shan", "xiang", "year"],
    },
    requireAuth: false,
    status: "active",
    description: "玄空飞星宅命盘，三元九运/山水向星/替卦/格局判断",
  },
  {
    id: "bazhai",
    name: "八宅风水",
    subtitle: "东西四宅·游年星",
    category: "fengshui",
    icon: "bazhai",
    route: "/tools/bazhai",
    visible: true,
    sortOrder: 31,
    inputSchema: {
      type: "object",
      properties: {
        birthYear:    { type: "number", label: "户主出生年", min: 1900, max: 2100 },
        gender:       { type: "enum", label: "性别", values: ["男", "女"] },
        zuoShan:      { type: "enum", label: "宅门坐向", values: ["坎","坤","震","巽","乾","兑","艮","离"] },
        liuNian:      { type: "boolean", label: "流年分析", default: false },
        liuNianYear:  { type: "number", label: "流年年份", required: false, min: 1900, max: 2100 },
      },
      required: ["birthYear", "gender", "zuoShan"],
    },
    requireAuth: false,
    status: "active",
    description: "八宅游年，东西四宅/命卦/八方吉凶/大游年歌诀",
  },
  {
    id: "dianzi-luopan",
    name: "电子罗盘",
    subtitle: "手机罗盘·精确测量",
    category: "fengshui",
    icon: "compass",
    route: "/tools/dianzi-luopan",
    visible: true,
    sortOrder: 32,
    inputSchema: {
      type: "object",
      properties: {
        type:                { type: "enum", label: "罗盘类型", values: ["sanhe", "sanyuan", "zonghe"], default: "zonghe" },
        degree:              { type: "number", label: "朝向角度", min: 0, max: 360, default: 0 },
        magneticCorrection:  { type: "boolean", label: "磁偏角修正", default: true },
        longitude:           { type: "number", label: "经度", required: false },
        latitude:            { type: "number", label: "纬度", required: false },
        buildYear:           { type: "number", label: "建造年份", required: false, min: 1900, max: 2100 },
      },
      required: ["type"],
    },
    requireAuth: false,
    status: "active",
    description: "三合/三元/综合罗盘，24山/纳甲/三合水法/流派风水指导",
  },
  {
    id: "liji-chi",
    name: "立极尺",
    subtitle: "立极规·风水测量",
    category: "fengshui",
    icon: "ruler",
    route: "/tools/liji-chi",
    visible: true,
    sortOrder: 33,
    inputSchema: {
      type: "object",
      properties: {
        chiType:   { type: "enum", label: "尺种类", values: ["luban", "dinglan", "mengong", "yacun"], default: "luban" },
        lengthCm:  { type: "number", label: "尺寸（厘米）", min: 0, max: 999 },
        usage:     { type: "string", label: "用途说明", required: false },
        batch:     { type: "boolean", label: "批量验算", default: false },
      },
      required: ["chiType", "lengthCm"],
    },
    requireAuth: false,
    status: "active",
    description: "鲁班尺/丁兰尺/门公尺/压白尺，四尺合一吉利尺寸推算",
  },
  {
    id: "shanxiang-ditu",
    name: "山向地图",
    subtitle: "地图叠加·风水罗盘",
    category: "fengshui",
    icon: "map-compass",
    route: "/tools/shanxiang-ditu",
    visible: true,
    sortOrder: 34,
    inputSchema: {
      type: "object",
      properties: {
        longitude:        { type: "number", label: "中心经度" },
        latitude:         { type: "number", label: "中心纬度" },
        direction:        { type: "number", label: "朝向角度", min: 0, max: 360 },
        zoom:             { type: "number", label: "缩放级别", min: 1, max: 20, default: 15, required: false },
        showShanOverlay:  { type: "boolean", label: "叠加二十四山", default: true },
        showJiuGong:      { type: "boolean", label: "叠加九宫格", default: false },
        buildYear:        { type: "number", label: "建造年份", required: false, min: 1900, max: 2100 },
      },
      required: ["longitude", "latitude", "direction"],
    },
    requireAuth: false,
    status: "active",
    description: "地图叠加罗盘，山向定点测量/形势分析/龙砂水穴向",
  },

  // ═══════════════ 星命 ═══════════════
  {
    id: "taiyi",
    name: "太乙神数",
    subtitle: "三式之首·国运预测",
    category: "xingming",
    icon: "taiyi",
    route: "/tools/taiyi",
    visible: true,
    sortOrder: 40,
    inputSchema: {
      type: "object",
      properties: {
        datetime: { type: "datetime", label: "起算时间", default: "now" },
        shiType:  { type: "enum", label: "太乙式", values: ["年计", "月计", "日计", "时计"], default: "时计" },
        yangDun:  { type: "boolean", label: "阳遁", default: false, required: false },
      },
      required: ["datetime", "shiType"],
    },
    requireAuth: false,
    status: "active",
    description: "五元六纪/十六神/八将/三算，三式之首的太乙神数",
  },
  {
    id: "qizheng-siyu",
    name: "七政四余",
    subtitle: "果老星宗·星命合参",
    category: "xingming",
    icon: "star",
    route: "/tools/qizheng-siyu",
    visible: true,
    sortOrder: 41,
    inputSchema: {
      type: "object",
      properties: {
        datetime:   { type: "datetime", label: "出生时间" },
        longitude:  { type: "number", label: "经度", required: false },
        latitude:   { type: "number", label: "纬度", required: false },
        gender:     { type: "enum", label: "性别", values: ["男", "女"] },
        trueSolar:  { type: "boolean", label: "真太阳时", default: false },
        system:     { type: "enum", label: "体系", values: ["guolao", "dongwei"], default: "guolao" },
      },
      required: ["datetime", "gender"],
    },
    requireAuth: false,
    status: "active",
    description: "十一曜/二十八宿/命宫十二宫/洞微大限，果老星宗体系",
  },
  {
    id: "wuyun-liuqi",
    name: "五运六气",
    subtitle: "中医运气·天时养生",
    category: "xingming",
    icon: "health",
    route: "/tools/wuyun-liuqi",
    visible: true,
    sortOrder: 42,
    inputSchema: {
      type: "object",
      properties: {
        year:         { type: "number", label: "年份", min: 1900, max: 2100 },
        showProcess:  { type: "boolean", label: "显示推算过程", default: false },
        currentDate:  { type: "datetime", label: "当日节气分析", required: false },
      },
      required: ["year"],
    },
    requireAuth: false,
    status: "active",
    description: "天干化运/地支化气/司天在泉/运气同化/病候养生",
  },

  // ═══════════════ 起名 ═══════════════
  {
    id: "qiming",
    name: "起名工具",
    subtitle: "八字起名·五行补益",
    category: "naming",
    icon: "baby",
    route: "/tools/qiming",
    visible: true,
    sortOrder: 50,
    inputSchema: {
      type: "object",
      properties: {
        surname:     { type: "string", label: "姓氏" },
        gender:      { type: "enum", label: "性别", values: ["男", "女"] },
        datetime:    { type: "datetime", label: "出生时间" },
        mode:        { type: "enum", label: "起名模式", values: ["auto", "manual", "fix"], default: "auto" },
        methods:     { type: "array", label: "起名方法", values: ["wuge","bazi-yongshen","shengxiao","yinyang-wuxing","zhouyi-gua","yinyun","ziyi","sancai","shici","kangxi","liushu"], default: ["wuge","bazi-yongshen"] },
        nameLength:  { type: "number", label: "名字字数", min: 1, max: 2, default: 2 },
        style:       { type: "enum", label: "偏好风格", values: ["古典", "现代", "诗词", "国学"], default: "古典", required: false },
        count:       { type: "number", label: "生成数量", min: 1, max: 50, default: 10, required: false },
        shengXiao:   { type: "enum", label: "生肖（姓名适配）", values: ["鼠","牛","虎","兔","龙","蛇","马","羊","猴","鸡","狗","猪"], required: false },
        birthYear:   { type: "number", label: "出生年（自动推生肖）", min: 1900, max: 2100, required: false },
      },
      required: ["surname", "gender", "datetime"],
    },
    requireAuth: false,
    status: "active",
    description: "多流派起名（五格/八字/生肖/音韵/诗词），生肖姓名学适配度评分",
  },
  {
    id: "xingming-jiexi",
    name: "姓名解析",
    subtitle: "五格数理·三才配置",
    category: "naming",
    icon: "name",
    route: "/tools/xingming-jiexi",
    visible: true,
    sortOrder: 51,
    inputSchema: {
      type: "object",
      properties: {
        surname:       { type: "string", label: "姓氏（支持复姓）" },
        givenName:     { type: "string", label: "名字" },
        kangXiStrokes: { type: "boolean", label: "使用康熙笔画", default: true },
        gender:        { type: "enum", label: "性别", values: ["男", "女"], required: false },
        shengXiao:     { type: "enum", label: "生肖", values: ["鼠","牛","虎","兔","龙","蛇","马","羊","猴","鸡","狗","猪"], required: false },
        birthYear:     { type: "number", label: "出生年（自动推导生肖）", min: 1900, max: 2100, required: false },
      },
      required: ["surname", "givenName"],
    },
    requireAuth: false,
    status: "active",
    description: "五格数理姓名学：天/人/地/总/外格，三才配置，81数理吉凶，生肖适配度分析",
  },
  {
    id: "company-naming",
    name: "公司起名",
    subtitle: "行业五行·工商核名",
    category: "naming",
    icon: "company",
    route: "/tools/company-naming",
    visible: true,
    sortOrder: 52,
    inputSchema: {
      type: "object",
      properties: {
        industry:      { type: "enum", label: "行业", values: ["科技","文化","贸易","餐饮","建筑","金融","教育","医疗","制造","农业","物流","传媒","咨询","设计","新能源","互联网"] },
        city:          { type: "string", label: "城市", required: false },
        companyForm:   { type: "enum", label: "组织形式", values: ["有限公司","股份有限公司","合伙企业","个人独资企业","个体工商户"], default: "有限公司" },
        ownerBirthday: { type: "string", label: "法人生日", required: false },
        style:         { type: "enum", label: "偏好风格", values: ["大气","雅致","现代","传统","创新"], default: "大气" },
        ziHaoLength:   { type: "enum", label: "字号字数", values: [2,3,4], default: 3 },
        keywords:      { type: "array", label: "自定义关键字", required: false },
      },
      required: ["industry"],
    },
    requireAuth: false,
    status: "active",
    description: "公司起名：行业五行匹配+81数理+康熙笔画+工商核名风险评估",
  },

  // ═══════════════ 工具字典 ═══════════════
  {
    id: "feigong-xiaoqimen",
    name: "飞宫小奇门",
    subtitle: "简化奇门·快速排盘",
    category: "utility",
    icon: "xiaoqimen",
    route: "/tools/feigong-xiaoqimen",
    visible: true,
    sortOrder: 60,
    inputSchema: {
      type: "object",
      properties: {
        datetime: { type: "datetime", label: "起局时间", default: "now" },
        method:   { type: "enum", label: "起局方式", values: ["shichen", "baoshu", "random"], default: "shichen" },
        number:   { type: "number", label: "报数", required: false },
        question: { type: "string", label: "所问事项", required: false },
      },
      required: ["method"],
    },
    requireAuth: false,
    status: "active",
    description: "简化奇门：九宫飞布，时辰起局，星门组合直断",
  },
  {
    id: "shoujihao-fenxi",
    name: "手机号分析",
    subtitle: "数字能量·号码吉凶",
    category: "utility",
    icon: "phone",
    route: "/tools/shoujihao-fenxi",
    visible: true,
    sortOrder: 61,
    inputSchema: {
      type: "object",
      properties: {
        phone:    { type: "string", label: "手机号码" },
        system:   { type: "enum", label: "分析体系", values: ["energy", "wuxing", "bagua", "all"], default: "all" },
        birthday: { type: "datetime", label: "生辰（选填）", required: false },
        gender:   { type: "enum", label: "性别", values: ["男", "女"], required: false },
      },
      required: ["phone"],
    },
    requireAuth: false,
    status: "active",
    description: "数字能量磁场/五行/八卦，八星吉凶+五行补益分析",
  },
  {
    id: "wannianli",
    name: "万年历·择吉",
    subtitle: "择吉黄历·诸事皆宜",
    category: "utility",
    icon: "calendar",
    route: "/tools/wannianli",
    visible: true,
    sortOrder: 62,
    inputSchema: {
      type: "object",
      properties: {
        date:       { type: "datetime", label: "查询日期", default: "now" },
        rangeType:  { type: "enum", label: "查询范围", values: ["day", "month", "range"], default: "month" },
        endDate:    { type: "datetime", label: "结束日期", required: false },
        shiXiang:   { type: "array", label: "择吉事项", values: ["jiehun","banqian","kaiye","dongtu","anmen","chuxing","qiuyi","zangmai","jisi"], required: false },
        zeJiMethods:{ type: "array", label: "择吉方法", values: ["huangli","xuan-ze","dong-gong","shen-sha","jian-chu","er-shi-ba-xiu","tian-de"], default: ["huangli"], required: false },
        bazi:       { type: "string", label: "生辰八字（个人择吉）", required: false },
      },
      required: ["date"],
    },
    requireAuth: false,
    status: "active",
    description: "全面万年历：黄历宜忌/建除十二值/二十八宿值日/择吉/神煞/月相/节气",
  },
  {
    id: "kangxi-zidian",
    name: "康熙字典",
    subtitle: "古文字典·字义查询",
    category: "utility",
    icon: "dictionary",
    route: "/tools/kangxi-zidian",
    visible: true,
    sortOrder: 63,
    inputSchema: {
      type: "object",
      properties: {
        queryType:    { type: "enum", label: "查询方式", values: ["char", "pinyin", "radical", "stroke", "wuxing"], default: "char" },
        query:        { type: "string", label: "查询内容" },
        wuXingFilter: { type: "enum", label: "五行筛选", values: ["金","木","水","火","土"], required: false },
        strokeMin:    { type: "number", label: "最小笔画", min: 1, max: 64, required: false },
        strokeMax:    { type: "number", label: "最大笔画", min: 1, max: 64, required: false },
      },
      required: ["queryType", "query"],
    },
    requireAuth: false,
    status: "active",
    description: "康熙字典全文检索，笔画/五行/拼音/部首多维查询",
  },
  {
    id: "hanzi-shaixuan",
    name: "汉字筛选",
    subtitle: "按属性筛选·起名助手",
    category: "utility",
    icon: "filter",
    route: "/tools/hanzi-shaixuan",
    visible: true,
    sortOrder: 64,
    inputSchema: {
      type: "object",
      properties: {
        wuXing:        { type: "enum", label: "五行", values: ["金","木","水","火","土"], required: false },
        strokeMin:     { type: "number", label: "最小笔画", min: 1, max: 64, required: false },
        strokeMax:     { type: "number", label: "最大笔画", min: 1, max: 64, required: false },
        radical:       { type: "string", label: "部首", required: false },
        tone:          { type: "array", label: "声调", required: false },
        meaningKeyword:{ type: "string", label: "字义关键词", required: false },
        commonOnly:    { type: "boolean", label: "仅常用字", default: false },
        nameOnly:      { type: "boolean", label: "仅姓名推荐字", default: false },
        zodiac:        { type: "enum", label: "生肖适配", values: ["鼠","牛","虎","兔","龙","蛇","马","羊","猴","鸡","狗","猪"], required: false },
        sortBy:        { type: "enum", label: "排序", values: ["stroke","pinyin","frequency","wuxing"], default: "stroke", required: false },
      },
      required: [],
    },
    requireAuth: false,
    status: "active",
    description: "多维度汉字筛选：五行/笔画/部首/声调/生肖/字义，起名利器",
  },
  {
    id: "xiaochengtu",
    name: "小成图",
    subtitle: "霍斐然·小成图预测",
    category: "divination",
    icon: "xiaochengtu",
    route: "/tools/xiaochengtu",
    visible: true,
    sortOrder: 12,
    inputSchema: {
      type: "object",
      properties: {
        datetime: { type: "datetime", label: "起卦时间", default: "now" },
        method:   { type: "enum", label: "起卦方式", values: ["shici", "baoshu", "zimu", "random"], default: "shici" },
        numbers:  { type: "array", label: "三个数字", required: false },
        chars:    { type: "string", label: "字母/汉字", required: false },
        question: { type: "string", label: "所问事项", required: false },
      },
      required: ["method"],
    },
    requireAuth: false,
    status: "active",
    description: "霍斐然小成图，九宫八卦天地盘/阖辟往来/正推旁推，不涉五行",
  },
  {
    id: "jinqianke",
    name: "金钱课",
    subtitle: "金钱卦·简易占卜",
    category: "divination",
    icon: "coin",
    route: "/tools/jinqianke",
    visible: true,
    sortOrder: 13,
    inputSchema: {
      type: "object",
      properties: {
        datetime: { type: "datetime", label: "起卦时间", default: "now" },
        method:   { type: "enum", label: "起卦方式", values: ["shoutou", "baoshu", "random"], default: "shoutou" },
        question: { type: "string", label: "所问事项", required: false },
      },
      required: ["method"],
    },
    requireAuth: false,
    status: "active",
    description: "六爻铜钱卦简版，本卦变卦互卦体用分析",
  },
  {
    id: "zhugeshenshu",
    name: "诸葛神数",
    subtitle: "384签·诸葛测字",
    category: "divination",
    icon: "zhuge",
    route: "/tools/zhugeshenshu",
    visible: true,
    sortOrder: 14,
    inputSchema: {
      type: "object",
      properties: {
        method:   { type: "enum", label: "起数方式", values: ["sanzi", "baoshu", "random"], default: "sanzi" },
        chars:    { type: "string", label: "三个汉字（sanzi时必填）", required: false },
        numbers:  { type: "array", label: "三个数字", required: false },
        question: { type: "string", label: "所问事项", required: false },
      },
      required: ["method"],
    },
    requireAuth: false,
    status: "active",
    description: "三字测字→折十法→384签文，签文解读步步拆解",
  },
  {
    id: "kongmingshengua",
    name: "孔明神卦",
    subtitle: "孔明签·占卜预测",
    category: "divination",
    icon: "kongming",
    route: "/tools/kongmingshengua",
    visible: true,
    sortOrder: 15,
    inputSchema: {
      type: "object",
      properties: {
        datetime: { type: "datetime", label: "起卦时间", default: "now" },
        method:   { type: "enum", label: "起卦方式", values: ["shici", "baoshu", "random"], default: "shici" },
        number:   { type: "number", label: "报数（1-384）", min: 1, max: 384, required: false },
        trigger:  { type: "string", label: "起卦事由", required: false },
        question: { type: "string", label: "所问事项", required: false },
      },
      required: ["method"],
    },
    requireAuth: false,
    status: "active",
    description: "孔明神卦签文预测，周易64卦系统解签",
  },
];

// ── 按分类分组 ──

export function getToolsDirectory(): { groups: ToolCategoryGroup[]; total: number } {
  const visible = ALL_TOOLS.filter((t) => t.visible);
  const grouped = new Map<string, ToolEntry[]>();

  for (const tool of visible) {
    const list = grouped.get(tool.category) || [];
    list.push(tool);
    grouped.set(tool.category, list);
  }

  const groups: ToolCategoryGroup[] = [];
  for (const [category, tools] of grouped) {
    const { label, icon } = CATEGORY_LABELS[category] || { label: category, icon: "default" };
    groups.push({
      category: category as ToolCategoryGroup["category"],
      label,
      icon,
      tools: tools.sort((a, b) => a.sortOrder - b.sortOrder),
    });
  }

  return { groups, total: visible.length };
}

/** 根据 ID 获取单个工具 */
export function getToolById(id: string): ToolEntry | undefined {
  return ALL_TOOLS.find((t) => t.id === id);
}

/** 根据分类获取工具 */
export function getToolsByCategory(category: string): ToolEntry[] {
  return ALL_TOOLS.filter((t) => t.category === category && t.visible);
}
