<template>
  <view class="page"><view class="nav"><text class="nb" @click="goBack">←</text><text class="nt">拼团详情</text><view style="width:48rpx"/></view>
    <view class="c"><view class="card"><text class="cn">{{gb.name}}</text><view class="cp-row"><text class="cp">¥{{gb.price}}</text><text class="co">¥{{gb.orig}}</text></view></view>
    <view class="card"><text class="ct">进行中的团</text>
      <view v-for="t in gb.teams" :key="t.id" class="tm"><text class="ta">{{t.leader[0]}}</text><view><text class="tn">{{t.leader}}</text><text class="td">{{t.desc}}</text></view><view class="tb" @click="join">参团</view></view></view>
    <view class="btn" @click="start">开新团</view></view></view>
</template>
<script setup lang="ts">import {ref} from 'vue';const gb=ref({name:'渊海子平精装版',price:68,orig:98,teams:[{id:1,leader:'易学爱好者',desc:'已3人·差2人·23:45'},{id:2,leader:'风水新手',desc:'已1人·差4人·12:30'}]});function join(){};function start(){uni.showToast({title:'开团成功'})};function goBack(){uni.navigateBack()}</script>
<style scoped>.page{background:#FAF8F5;min-height:100vh}.nav{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:56px;background:#fff;border-bottom:1px solid #E8E0D5}.nb{font-size:36rpx;color:#2C2C2C}.nt{font-size:32rpx;font-weight:600}.c{padding:24rpx}.card{background:#fff;border-radius:16rpx;padding:24rpx;margin-bottom:16rpx;box-shadow:0 2rpx 8rpx rgba(0,0,0,.03)}.cn{font-size:30rpx;font-weight:600;color:#2C2C2C;display:block}.cp-row{display:flex;align-items:baseline;gap:12rpx;margin-top:12rpx}.cp{font-size:44rpx;font-weight:700;color:#C41E3A}.co{font-size:26rpx;color:#999;text-decoration:line-through}.ct{font-size:26rpx;font-weight:600;color:#2C2C2C;margin-bottom:16rpx;display:block}.tm{display:flex;align-items:center;gap:12rpx;padding:16rpx 0;border-bottom:1px solid #F5F1EB}.ta{width:56rpx;height:56rpx;border-radius:50%;background:#F5F1EB;display:flex;align-items:center;justify-content:center;font-size:24rpx;color:#999}.tn{font-size:26rpx;color:#2C2C2C;display:block}.td{font-size:22rpx;color:#999}.tb{padding:10rpx 24rpx;background:#C41E3A;color:#fff;border-radius:40rpx;font-size:22rpx}.btn{padding:28rpx;text-align:center;background:linear-gradient(90deg,#C41E3A,#E74C3C);color:#fff;border-radius:24rpx;font-size:28rpx;font-weight:600}
</style>
