-- 仅本地合成试点；不进入已有 Prisma 迁移历史。
CREATE TABLE IF NOT EXISTS identity(space TEXT PRIMARY KEY, config TEXT NOT NULL, digest TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users(id TEXT NOT NULL, scope TEXT NOT NULL, role TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 1, phone TEXT, PRIMARY KEY(id,scope));
CREATE TABLE IF NOT EXISTS resources(id TEXT PRIMARY KEY, scope TEXT NOT NULL, kind TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS circles(id TEXT PRIMARY KEY, scope TEXT NOT NULL, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY, scope TEXT NOT NULL, userId TEXT NOT NULL, snapshot TEXT NOT NULL, status TEXT NOT NULL, entitlement INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS callbacks(event TEXT PRIMARY KEY, orderId TEXT NOT NULL, action TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS chats(id TEXT PRIMARY KEY, scope TEXT NOT NULL, userId TEXT NOT NULL, agentId TEXT NOT NULL, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY, scope TEXT NOT NULL, revision INTEGER NOT NULL, state TEXT NOT NULL, kind TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS exports(id TEXT PRIMARY KEY, scope TEXT NOT NULL, userId TEXT NOT NULL, grantHash TEXT NOT NULL, untilAt INTEGER NOT NULL, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS assets(id TEXT PRIMARY KEY, scope TEXT NOT NULL, userId TEXT NOT NULL, body TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT, scope TEXT NOT NULL, actor TEXT NOT NULL, action TEXT NOT NULL, target TEXT NOT NULL, at INTEGER NOT NULL);
