import { setTimeout as sleep } from "node:timers/promises";
import { PrismaClient, InstituteRole } from "@prisma/client";
import { PrismaService } from "../../prisma/prisma.service";
import { InstituteBoardService } from "./institute-board.service";
import { InstituteController } from "./institute.controller";
import { clearCircleMembershipCaches } from "../circle/services/circle-membership-cache.task";
const testUrl = process.env.ENTITLEMENT_NOTICE_TEST_DATABASE_URL;
if (testUrl) { const u = new URL(testUrl); if (u.protocol !== "postgresql:" || u.hostname !== "127.0.0.1" || u.port !== "55477" || u.username !== "qa_voice" || !u.pathname.startsWith("/entitlement_notice_qa_")) throw new Error("私董会仅允许本机合成库"); }
jest.setTimeout(60000);
(testUrl ? describe : describe.skip)("私董会当前权限归属与缓存待办", () => {
  let db: PrismaClient;
  const users: string[] = [], institutes: string[] = [];
  const entries = ["create", "disband", "list"] as const;
  type Entry = typeof entries[number];
  const managementRoles = ["PRESIDENT", "VICE_PRESIDENT", "SECRETARY_GENERAL"] as const;
  const service = (client: unknown = db, redis?: unknown) => new InstituteBoardService(client as PrismaService, redis as any);
  const fixture = async (entry: Entry) => {
    const actor = await db.user.create({ data: { nickname: "合成私董会管理者" } }), leader = await db.user.create({ data: { nickname: "合成组长" } }), other = await db.user.create({ data: { nickname: "合成其他账号" } }); users.push(actor.id, leader.id, other.id);
    const institute = await db.institute.create({ data: { name: "合成私董会院", adminUserId: leader.id } }), elsewhere = await db.institute.create({ data: { name: "合成另一院", adminUserId: leader.id } }); institutes.push(institute.id, elsewhere.id);
    const manager = await db.instituteMember.create({ data: { userId: actor.id, instituteId: institute.id, role: "PRESIDENT", status: "ACTIVE", joinYear: 2026 } }), member = await db.instituteMember.create({ data: { userId: leader.id, instituteId: institute.id, role: "TYPE_A", status: "ACTIVE", seatType: "LECTURE", joinYear: 2026 } });
    const dto = { name: "合成闭门小组", topic: "合成内部议题", leaderId: leader.id, memberLimit: 8 };
    const group = entry === "create" ? undefined : await service().createBoardGroup(actor.id, dto);
    return { actorId: actor.id, leaderId: leader.id, otherId: other.id, instituteId: institute.id, elsewhereId: elsewhere.id, managerId: manager.id, leaderMemberId: member.id, dto, groupId: group?.id, circleId: group?.circleId };
  };
  type Fixture = Awaited<ReturnType<typeof fixture>>;
  const invoke = (f: Fixture, entry: Entry, client: unknown = db, afterSnapshot?: () => Promise<unknown>, redis?: unknown) => {
    const svc = service(client, redis);
    if (afterSnapshot) { const original = (svc as any).assertManagement.bind(svc); (svc as any).assertManagement = async (...args: unknown[]) => { const snapshot = await original(...args); await afterSnapshot(); return snapshot; }; }
    const controller = new InstituteController(undefined!, undefined!, svc, undefined!), request = { user: { id: f.actorId, roles: [] } } as any;
    if (entry === "create") return controller.createBoardGroup(request, f.dto);
    if (entry === "disband") return controller.disbandBoardGroup(request, f.groupId!);
    return svc.listBoardGroups(f.actorId);
  };
  const checkCreated = async (f: Fixture) => {
    expect(await db.instituteBoardGroup.count()).toBe(1); expect(await db.circle.count()).toBe(1); expect(await db.circleMember.count()).toBe(1);
    const group = await db.instituteBoardGroup.findFirstOrThrow(), circle = await db.circle.findUniqueOrThrow({ where: { id: group.circleId } }), owner = await db.circleMember.findFirstOrThrow();
    expect(group.instituteId).toBe(f.instituteId); expect(group.leaderId).toBe(f.leaderId); expect(group.topic).toBe("合成内部议题"); expect(circle.ownerId).toBe(f.leaderId); expect(circle.type).toBe("FREE"); expect(circle.needApproval).toBe(true); expect(circle.status).toBe("ACTIVE"); expect(circle.memberCount).toBe(1); expect(owner.userId).toBe(f.leaderId); expect(owner.role).toBe("OWNER"); expect(await db.userRole.count({ where: { userId: f.leaderId, roleType: "CIRCLE_OWNER", bindId: circle.id } })).toBe(1);
    const queue = await db.$queryRaw<Array<{ n: number }>>`SELECT count(*)::int AS n FROM "CircleMembershipCacheInvalidation"`; expect(queue[0].n).toBe(1); expect(await db.userWallet.count()).toBe(0);
  };
  const pristine = async (f: Fixture, entry: Entry) => { expect(await db.instituteBoardGroup.count()).toBe(entry === "create" ? 0 : 1); expect(await db.circle.count()).toBe(entry === "create" ? 0 : 1); if (entry === "disband") expect((await db.instituteBoardGroup.findUniqueOrThrow({ where: { id: f.groupId } })).status).toBe("ACTIVE"); };
  const stale = (delegate: "instituteMember" | "instituteBoardGroup", method: string, predicate: (args: any[]) => boolean, mutate: () => Promise<unknown>) => { let done = false; return new Proxy(db, { get(target, key) { const value = Reflect.get(target, key); if (key === delegate) return new Proxy(value, { get(model, name) { const fn = Reflect.get(model, name); if (name === method) return async (...args: any[]) => { const snapshot = await Reflect.apply(fn, model, args); if (!done && predicate(args)) { done = true; await mutate(); } return snapshot; }; return typeof fn === "function" ? fn.bind(model) : fn; } }); return typeof value === "function" ? value.bind(target) : value; } }); };
  const managerChanges = ["降级", "停用", "改属", "改院", "删除会籍", "封禁账号", "停用账号", "删除账号"];
  const mutateMember = async (f: Fixture, name: string, leader = false, client: any = db) => {
    const id = leader ? f.leaderMemberId : f.managerId, userId = leader ? f.leaderId : f.actorId;
    if (name === "删除会籍" || name === "删除账号") { await client.instituteMember.delete({ where: { id } }); if (name === "删除账号") return client.user.delete({ where: { id: userId } }); return; }
    if (name === "封禁账号" || name === "停用账号") return client.user.update({ where: { id: userId }, data: { status: name === "封禁账号" ? "BANNED" : "DISABLED" } });
    return client.instituteMember.update({ where: { id }, data: name === "降级" ? { role: "TYPE_A" } : name === "停用" ? { status: "SUSPENDED" } : name === "改属" ? { userId: f.otherId } : name === "改院" ? { instituteId: f.elsewhereId } : { seatType: "STUDY" } });
  };
  beforeAll(async () => { db = new PrismaClient({ datasources: { db: { url: testUrl } } }); const [id] = await db.$queryRaw<Array<{ port: number; db: string; user: string }>>`SELECT inet_server_port() AS port, current_database() AS db, current_user AS "user"`; expect(id.port).toBe(55477); expect(id.db.startsWith("entitlement_notice_qa_")).toBe(true); expect(id.user).toBe("qa_voice"); });
  afterEach(async () => { const circles = await db.circle.findMany({ select: { id: true } }); const ids = circles.map(c => c.id); await db.$executeRaw`DELETE FROM "CircleMembershipCacheInvalidation"`; await db.instituteBoardGroup.deleteMany({ where: { instituteId: { in: institutes } } }); await db.userRole.deleteMany({ where: { userId: { in: users } } }); await db.circleMember.deleteMany({ where: { circleId: { in: ids } } }); await db.circle.deleteMany({ where: { id: { in: ids } } }); await db.instituteMember.deleteMany({ where: { instituteId: { in: institutes } } }); await db.institute.deleteMany({ where: { id: { in: institutes.splice(0) } } }); await db.user.deleteMany({ where: { id: { in: users.splice(0) } } }); });
  afterAll(async () => { await db.$disconnect(); });
  it.each((["create", "disband"] as const).flatMap(entry => managementRoles.map(role => [entry, role] as const)))("%s当前管理角色%s可操作", async (entry, role) => { const f = await fixture(entry); await db.instituteMember.update({ where: { id: f.managerId }, data: { role } }); await invoke(f, entry); if (entry === "create") await checkCreated(f); else { expect((await db.instituteBoardGroup.findUniqueOrThrow({ where: { id: f.groupId } })).status).toBe("DISBANDED"); expect(await db.circle.count()).toBe(1); expect(await db.circleMember.count()).toBe(1); } });
  it.each(Object.values(InstituteRole))("原任意ACTIVE成员角色%s可见私董会", async role => { const f = await fixture("list"); await db.instituteMember.update({ where: { id: f.managerId }, data: { role, seatType: "STUDY" } }); const value: any = await invoke(f, "list"); expect(value.items[0].topic).toBe("合成内部议题"); expect(value.items[0].memberCount).toBe(1); expect(value.items[0].joined).toBe(false); });
  it.each((["create", "disband"] as const).flatMap(entry => managerChanges.map(name => [entry, name] as const)))("%s真实管理快照后%s拒绝", async (entry, name) => { const f = await fixture(entry); await expect(invoke(f, entry, db, () => mutateMember(f, name))).rejects.toThrow(); await pristine(f, entry); });
  it.each(["停用", "改属", "改院", "转研修", "删除会籍", "封禁账号", "停用账号"])("组长快照后%s拒绝建组", async name => { const f = await fixture("create"); const client = stale("instituteMember", "findFirst", args => args[0].where.userId === f.leaderId, () => mutateMember(f, name, true)); await expect(invoke(f, "create", client)).rejects.toThrow(); await pristine(f, "create"); });
  it.each(["停用", "改属", "改院", "删除会籍", "封禁账号", "停用账号", "删除账号"])("列表成员快照后%s拒绝内部信息", async name => { const f = await fixture("list"); const client = stale("instituteMember", "findFirst", () => true, () => mutateMember(f, name)); await expect(invoke(f, "list", client)).rejects.toThrow(); });
  it.each(["改院", "换组长", "换圈", "已解散", "删除"])("小组快照后%s拒绝旧请求解散", async name => { const f = await fixture("disband"); let newCircleId: string | undefined;
    const client = stale("instituteBoardGroup", "findUnique", () => true, async () => { if (name === "删除") return db.instituteBoardGroup.delete({ where: { id: f.groupId } }); if (name === "换圈") { const circle = await db.circle.create({ data: { name: "合成新圈", intro: "合成", ownerId: f.leaderId } }); newCircleId = circle.id; } return db.instituteBoardGroup.update({ where: { id: f.groupId }, data: name === "改院" ? { instituteId: f.elsewhereId } : name === "换组长" ? { leaderId: f.otherId } : name === "换圈" ? { circleId: newCircleId } : { status: "DISBANDED" } }); });
    await expect(invoke(f, "disband", client)).rejects.toThrow(name === "已解散" ? "已解散" : name === "删除" ? "不存在" : "归属已变化"); const current = await db.instituteBoardGroup.findUnique({ where: { id: f.groupId } }); expect(current?.status).toBe(name === "删除" ? undefined : name === "已解散" ? "DISBANDED" : "ACTIVE");
  });
  it.each(entries)("%s原关闭院规则保持", async entry => { const f = await fixture(entry); await db.institute.update({ where: { id: f.instituteId }, data: { status: "CLOSED" } }); await invoke(f, entry); if (entry === "create") await checkCreated(f); });
  it("管理者可同时为组长，OWNER与角色仅一份", async () => { const f = await fixture("create"); f.leaderId = f.actorId; f.dto.leaderId = f.actorId; await invoke(f, "create"); await checkCreated(f); });
  it("合法管理角色更换后建组", async () => { const f = await fixture("create"); await invoke(f, "create", db, () => db.instituteMember.update({ where: { id: f.managerId }, data: { role: "VICE_PRESIDENT" } })); await checkCreated(f); });
  it("缓存实际调用失败仍返回已提交小组，待办可恢复", async () => { const f = await fixture("create"), failed = { clearCircleMembershipShared: jest.fn(async () => { throw new Error("合成共享缓存失败"); }) }; const group: any = await invoke(f, "create", db, undefined, failed); expect(group.id).toBeDefined(); await checkCreated(f); expect(failed.clearCircleMembershipShared).toHaveBeenCalledTimes(1); const before = await db.$queryRaw<Array<{ clearedAt: Date | null }>>`SELECT "clearedAt" FROM "CircleMembershipCacheInvalidation"`; expect(before[0].clearedAt).toBeNull(); const recovered = { clearCircleMembershipShared: jest.fn(async () => {}) }; expect(await clearCircleMembershipCaches(db as unknown as PrismaService, recovered as any)).toBe(1); expect(await clearCircleMembershipCaches(db as unknown as PrismaService, recovered as any)).toBe(0); expect(await db.instituteBoardGroup.count()).toBe(1); expect(await db.circle.count()).toBe(1); });
  it("无缓存连接仍保存恢复待办", async () => { const f = await fixture("create"); await invoke(f, "create"); await checkCreated(f); const rows = await db.$queryRaw<Array<{ clearedAt: Date | null }>>`SELECT "clearedAt" FROM "CircleMembershipCacheInvalidation"`; expect(rows[0].clearedAt).toBeNull(); });
  it.each(["OWNER写入后", "角色写入后", "待办写入后", "小组写入后"])("%s故障全部回滚", async name => { const f = await fixture("create"); const client = new Proxy(db, { get(target, key) { const value = Reflect.get(target, key); if (key === "$transaction") return (callback: any) => target.$transaction(async tx => {
    const wrapped = new Proxy(tx, { get(raw, field) { const delegate = Reflect.get(raw, field); if (field === "circle" || field === "userRole" || field === "instituteBoardGroup") return new Proxy(delegate, { get(model, method) { const fn = Reflect.get(model, method); if ((name === "OWNER写入后" && field === "circle" && method === "create") || (name === "角色写入后" && field === "userRole" && method === "upsert") || (name === "小组写入后" && field === "instituteBoardGroup" && method === "create")) return async (...args: unknown[]) => { await Reflect.apply(fn, model, args); throw new Error("合成事务写入后故障"); }; return typeof fn === "function" ? fn.bind(model) : fn; } }); if (name === "待办写入后" && field === "$executeRaw") return async (...args: unknown[]) => { await Reflect.apply(delegate, raw, args); throw new Error("合成事务写入后故障"); }; return typeof delegate === "function" ? delegate.bind(raw) : delegate; } }); return callback(wrapped);
  }); return typeof value === "function" ? value.bind(target) : value; } }); await expect(invoke(f, "create", client)).rejects.toThrow("合成事务写入后故障"); await pristine(f, "create"); expect(await db.circleMember.count()).toBe(0); expect(await db.userRole.count()).toBe(0); const [row] = await db.$queryRaw<Array<{ n: number }>>`SELECT count(*)::int AS n FROM "CircleMembershipCacheInvalidation"`; expect(row.n).toBe(0); });
  it("并发解散仅一次成功，圈子本体与OWNER保留", async () => { const f = await fixture("disband"); const results = await Promise.allSettled([invoke(f, "disband"), invoke(f, "disband")]); expect(results.filter(r => r.status === "fulfilled")).toHaveLength(1); expect(await db.circle.count()).toBe(1); expect(await db.circleMember.count()).toBe(1); expect(await db.userRole.count()).toBe(1); });
  const gate = () => { let release!: () => void; const promise = new Promise<void>(resolve => { release = resolve; }); return { promise, release }; };
  const waitLocked = async (pid: number) => { for (let i = 0; i < 150; i++) { const [r] = await db.$queryRaw<Array<{ waiting: boolean }>>`SELECT EXISTS(SELECT 1 FROM pg_stat_activity WHERE pid=${pid} AND wait_event_type='Lock') AS waiting`; if (r.waiting) return; await sleep(20); } throw new Error("未观测真实行锁等待"); };
  const watched = (entry: Entry, ready: { release: () => void }, release: Promise<void>, pid: (id: number) => void, pause = false) => new Proxy(db, { get(target, key) { const value = Reflect.get(target, key); if (key === "$transaction") return (callback: any) => target.$transaction(async tx => { const [r] = await tx.$queryRaw<Array<{ pid: number }>>`SELECT pg_backend_pid() AS pid`; pid(r.pid); if (!pause) ready.release(); let paused = false; const wrapped = new Proxy(tx, { get(raw, field) { const delegate = Reflect.get(raw, field); const selected = entry === "create" ? "circle" : "instituteBoardGroup"; if (pause && field === selected) return new Proxy(delegate, { get(model, method) { const fn = Reflect.get(model, method); if ((method === "create" || method === "update" || method === "findMany") && !paused) return async (...args: unknown[]) => { paused = true; ready.release(); await release; return Reflect.apply(fn, model, args); }; return typeof fn === "function" ? fn.bind(model) : fn; } }); return typeof delegate === "function" ? delegate.bind(raw) : delegate; } }); return callback(wrapped); }, { timeout: 15000 }); return typeof value === "function" ? value.bind(target) : value; } });
  const lockKinds = entries.flatMap(entry => (entry === "create" ? ["账号", "管理会籍", "组长会籍", "组长账号"] : entry === "disband" ? ["账号", "管理会籍", "小组"] : ["账号", "成员会籍"]).map(kind => [entry, kind] as const));
  const lockedChange = async (tx: any, f: Fixture, kind: string) => { if (kind === "账号" || kind === "组长账号") return tx.user.update({ where: { id: kind === "账号" ? f.actorId : f.leaderId }, data: { status: "BANNED" } }); if (kind === "小组") return tx.instituteBoardGroup.update({ where: { id: f.groupId }, data: { instituteId: f.elsewhereId } }); return tx.instituteMember.update({ where: { id: kind === "组长会籍" ? f.leaderMemberId : f.managerId }, data: { status: "SUSPENDED" } }); };
  it.each(lockKinds)("%s%s先变更，操作等待后拒绝", async (entry, kind) => { const f = await fixture(entry), ready = gate(), release = gate(), readerReady = gate(); let pid = 0; const writer = db.$transaction(async tx => { await lockedChange(tx, f, kind); ready.release(); await release.promise; }, { timeout: 15000 }); await ready.promise; const reader = invoke(f, entry, watched(entry, readerReady, Promise.resolve(), id => { pid = id; })).then(value => ({ value, error: undefined }), error => ({ value: undefined, error })); try { await readerReady.promise; await waitLocked(pid); } finally { release.release(); } await writer; expect((await reader).error).toBeDefined(); });
  it.each(lockKinds)("%s先授权持锁，%s变更等待提交", async (entry, kind) => { const f = await fixture(entry), ready = gate(), release = gate(), writerReady = gate(); let pid = 0; const reader = invoke(f, entry, watched(entry, ready, release.promise, () => {}, true)); await ready.promise; const writer = db.$transaction(async tx => { const [r] = await tx.$queryRaw<Array<{ pid: number }>>`SELECT pg_backend_pid() AS pid`; pid = r.pid; writerReady.release(); await lockedChange(tx, f, kind); }, { timeout: 15000 }); try { await writerReady.promise; await waitLocked(pid); } finally { release.release(); } await reader; await writer; });
});
