<template>
  <view class="page"><view class="nav"><text class="nb" @click="goBack">←</text><text class="nt">古籍详情</text><view style="width:48rpx"/></view>
    <view class="c"><view class="card"><text class="cn">{{b.title}}</text><text class="cm">{{b.author}}·{{b.dynasty}}</text><text class="cd">{{b.desc}}</text></view>
    <view class="card"><text class="ct">目录</text><view v-for="c in b.chapters" :key="c.id" class="cr"><text class="ci">{{c.id}}</text><text class="cn2">{{c.title}}</text></view></view>
    <view class="bb"><view class="bbb" @click="startRead">开始阅读</view></view></view></view>
</template>
<script setup lang="ts">import {ref} from 'vue';const b=ref({title:'渊海子平',author:'徐升',dynasty:'宋',desc:'八字命理学经典著作',chapters:[{id:1,title:'卷一·论天干地支'},{id:2,title:'卷二·论格局'}]});function startRead(){uni.navigateTo({url:'/pages/reader/id-detail/index'})};function goBack(){uni.navigateBack()}</script>
<style scoped>.page{background:#FAF8F5;min-height:100vh}.nav{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:56px;background:#fff;border-bottom:1px solid #E8E0D5}.nb{font-size:36rpx;color:#2C2C2C}.nt{font-size:32rpx;font-weight:600}.c{padding:24rpx}.card{background:#fff;border-radius:20rpx;padding:28rpx;margin-bottom:20rpx;box-shadow:0 2rpx 12rpx rgba(0,0,0,.04)}.cn{font-size:36rpx;font-weight:600;color:#2C2C2C;display:block}.cm{font-size:24rpx;color:#999;margin:8rpx 0}.cd{font-size:26rpx;color:#666;line-height:1.6}.ct{font-size:28rpx;font-weight:600;color:#2C2C2C;margin-bottom:16rpx;display:block}.cr{display:flex;gap:16rpx;padding:16rpx 0;border-bottom:1px solid #F5F1EB}.ci{width:48rpx;height:48rpx;border-radius:50%;background:rgba(196,30,58,.1);display:flex;align-items:center;justify-content:center;font-size:22rpx;color:#C41E3A}.cn2{font-size:26rpx;color:#2C2C2C}.bb{position:fixed;bottom:0;left:0;right:0;padding:20rpx 24rpx;background:#fff;border-top:1px solid #E8E0D5;z-index:50}.bbb{padding:28rpx;text-align:center;background:linear-gradient(90deg,#C41E3A,#E74C3C);color:#fff;border-radius:40rpx;font-size:28rpx;font-weight:600}
</style>
