<template>
  <view class="page">
    <view class="body">
      <text class="title">选择你感兴趣的领域</text><text class="sub">选择3-8个标签，我们将为你推荐优质内容</text>
      <view class="tags"><text v-for="t in interests" :key="t.key" class="tag" :class="{sel:selected.includes(t.key)}" @click="toggle(t.key)">{{t.icon}} {{t.label}}</text></view>
      <view class="bottom"><text class="hint">已选{{selected.length}}个</text><view class="btn" :class="{dis:selected.length<3}" @click="handleSubmit">{{selected.length<3?'最少选3个':'开始探索'}}</view></view>
    </view>
  </view>
</template>
<script setup lang="ts">import {ref} from 'vue';const selected=ref<string[]>([]);const interests=[{key:'classical',label:'经典国学',icon:'📖'},{key:'poetry',label:'诗词歌赋',icon:'📜'},{key:'bazi',label:'八字命理',icon:'🏮'},{key:'ziwei',label:'紫微斗数',icon:'⭐'},{key:'fengshui',label:'风水堪舆',icon:'🏠'},{key:'health',label:'中医养生',icon:'🌿'},{key:'martial',label:'武术太极',icon:'👊'},{key:'tea',label:'茶道文化',icon:'🍵'},{key:'calligraphy',label:'书法艺术',icon:'🖌️'},{key:'painting',label:'国画山水',icon:'🎨'},{key:'music',label:'古典音乐',icon:'🎵'},{key:'history',label:'历史研究',icon:'📚'},{key:'qimen',label:'奇门遁甲',icon:'🧭'},{key:'liuyao',label:'六爻预测',icon:'🔮'},{key:'name',label:'姓名学',icon:'📛'},{key:'fortune',label:'每日运势',icon:'🌟'},{key:'course',label:'国学课程',icon:'🎓'},{key:'live',label:'知识直播',icon:'📻'}];function toggle(key:string){const i=selected.value.indexOf(key);i>-1?selected.value.splice(i,1):selected.value.length<8&&selected.value.push(key)};function handleSubmit(){if(selected.value.length<3)return;uni.reLaunch({url:'/pages/index/index'})}</script>
<style scoped>.page{background:linear-gradient(180deg,#C41E3A,#8B0000);min-height:100vh;display:flex;align-items:center}.body{padding:48rpx 32rpx;text-align:center;width:100%}.title{font-size:40rpx;font-weight:700;color:#fff;display:block;margin-bottom:12rpx}.sub{font-size:26rpx;color:rgba(255,255,255,.7);display:block;margin-bottom:48rpx}.tags{display:flex;flex-wrap:wrap;gap:16rpx;justify-content:center;margin-bottom:80rpx}.tag{padding:16rpx 28rpx;border-radius:40rpx;font-size:24rpx;color:rgba(255,255,255,.8);border:1px solid rgba(255,255,255,.3);display:flex;align-items:center;gap:8rpx}.tag.sel{background:#fff;color:#C41E3A;border-color:#fff}.hint{font-size:24rpx;color:rgba(255,255,255,.6);display:block;margin-bottom:16rpx}.btn{padding:28rpx;background:#fff;color:#C41E3A;border-radius:40rpx;font-size:28rpx;font-weight:600}.btn.dis{opacity:.5}</style>
