// 菜单配置 — 单一声源，按角色控制可见性
// roles 为空表示所有已登录用户可见

export interface MenuItem {
  title: string;
  icon?: string;
  path?: string;
  roles?: string[];
  children?: MenuItem[];
}

const ALL_ADMIN = [
  "SUPER_ADMIN",
  "OPERATION_ADMIN",
  "CONTENT_AUDITOR",
  "FINANCE_ADMIN",
  "CUSTOMER_SERVICE",
  "GOODS_AUDITOR",
];

export const MENU_CONFIG: MenuItem[] = [
  {
    title: "工作台",
    icon: "DataBoard",
    path: "/dashboard",
    roles: ALL_ADMIN,
  },
  {
    title: "内容管理",
    icon: "Document",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "CONTENT_AUDITOR"],
    children: [
      { title: "内容列表", path: "/contents" },
      { title: "内容审核", path: "/contents/audit", roles: ["SUPER_ADMIN", "CONTENT_AUDITOR"] },
      { title: "推荐管理", path: "/contents/recommend", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "品类管理", path: "/categories", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
    ],
  },
  {
    title: "古籍管理",
    icon: "Notebook",
    path: "/classics",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "CONTENT_AUDITOR"],
  },
  {
    title: "诗词雅集",
    icon: "Reading",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "CONTENT_AUDITOR"],
    children: [
      { title: "诗词管理", path: "/poetry" },
      { title: "诗词分类", path: "/poetry/categories", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "诗单管理", path: "/poetry/collections" },
    ],
  },
  {
    title: "社区管理",
    icon: "ChatDotRound",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "CONTENT_AUDITOR"],
    children: [
      { title: "圈子管理", path: "/circles" },
      { title: "圈子退款审核", path: "/circle-refunds", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "视频管理", path: "/videos" },
      { title: "直播管理", path: "/lives" },
      { title: "付费问答", path: "/questions" },
    ],
  },
  {
    title: "排盘工具",
    icon: "Timer",
    roles: ALL_ADMIN,
    children: [
      { title: "八字排盘", path: "/bazi" },
      { title: "紫微排盘", path: "/ziwei" },
      { title: "排盘记录", path: "/paipan-records" },
      { title: "Bot管理", path: "/bots" },
    ],
  },
  {
    title: "赛事管理",
    icon: "Trophy",
    path: "/competitions",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN"],
  },
  {
    title: "教学管理",
    icon: "Reading",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "CONTENT_AUDITOR"],
    children: [
      { title: "课程管理", path: "/courses" },
      { title: "课程分类", path: "/courses/categories", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "讲师认证审核", path: "/teacher/certifications", roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "CONTENT_AUDITOR"] },
    ],
  },
  {
    title: "用户管理",
    icon: "User",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "CUSTOMER_SERVICE"],
    children: [
      { title: "用户列表", path: "/users" },
      { title: "实名审核", path: "/users/identity", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "用户推送", path: "/users/push", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "兴趣分析", path: "/users/interests", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
    ],
  },
  {
    title: "文章管理",
    icon: "Postcard",
    path: "/articles",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "CONTENT_AUDITOR"],
  },
  {
    title: "交易管理",
    icon: "ShoppingCart",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "FINANCE_ADMIN", "GOODS_AUDITOR"],
    children: [
      { title: "订单管理", path: "/orders" },
      { title: "退款审核", path: "/orders/refund" },
      { title: "支付流水", path: "/orders/payments" },
    ],
  },
  {
    title: "会员管理",
    icon: "Medal",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "FINANCE_ADMIN"],
    children: [
      { title: "购买记录", path: "/member/purchases" },
      { title: "会员统计", path: "/member/stats" },
      { title: "会员管理", path: "/member/manage", roles: ["SUPER_ADMIN"] },
    ],
  },
  {
    title: "商城管理",
    icon: "Goods",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "GOODS_AUDITOR"],
    children: [
      { title: "商品管理", path: "/products" },
      { title: "商品品控", path: "/shop/product-audit", roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "GOODS_AUDITOR"] },
      { title: "优惠券管理", path: "/coupons" },
    ],
  },
  {
    title: "创作者中心",
    icon: "VideoCamera",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN"],
    children: [
      { title: "创作者管理", path: "/creator/list" },
      { title: "创作者提现", path: "/creator/withdrawals" },
    ],
  },
  {
    title: "商家管理",
    icon: "Shop",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN"],
    children: [
      { title: "商家列表", path: "/merchants" },
      { title: "商家协议", path: "/merchants/agreements" },
    ],
  },
  {
    title: "营销管理",
    icon: "Present",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN"],
    children: [
      { title: "秒杀活动", path: "/marketing/flash-sales" },
      { title: "拼团活动", path: "/marketing/group-buys" },
      { title: "优惠券模板", path: "/marketing/coupons" },
      { title: "限时折扣", path: "/marketing/discounts" },
      { title: "营销活动", path: "/marketing/activities" },
      { title: "微页面管理", path: "/marketing/pages" },
    ],
  },
  {
    title: "财务管理",
    icon: "Money",
    roles: ["SUPER_ADMIN", "FINANCE_ADMIN"],
    children: [
      { title: "营收总览", path: "/revenue" },
      { title: "充值记录", path: "/recharges" },
      { title: "礼物管理", path: "/gifts" },
      { title: "对账中心", path: "/finance/reconciliation" },
      { title: "发票管理", path: "/finance/invoices" },
      { title: "结算单", path: "/finance/settlements" },
      { title: "提现审批", path: "/finance/withdrawals" },
      { title: "财务报表", path: "/finance/reports" },
      { title: "资金冻结", path: "/finance/freeze" },
      { title: "资金审批中心", path: "/finance/fund-approval", roles: ["SUPER_ADMIN", "FINANCE_ADMIN"] },
      { title: "分佣规则", path: "/finance/settlement-rules", roles: ["SUPER_ADMIN", "FINANCE_ADMIN"] },
      { title: "汇付天下支付", path: "/huifu", roles: ["SUPER_ADMIN", "FINANCE_ADMIN"] },
    ],
  },
  {
    title: "营销分佣",
    icon: "Share",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "FINANCE_ADMIN"],
    children: [
      { title: "佣金配置", path: "/commission-config" },
      { title: "提现审核", path: "/withdrawals" },
    ],
  },
  {
    title: "风控中心",
    icon: "Warning",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "CUSTOMER_SERVICE"],
    children: [
      { title: "预警中心", path: "/risk/alerts" },
      { title: "哨兵告警", path: "/sentinel/alerts", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "风控规则", path: "/risk/rules" },
      { title: "刷单识别", path: "/risk/fraud" },
      { title: "行为轨迹", path: "/risk/timeline" },
      { title: "申诉处理", path: "/risk/appeals" },
    ],
  },
  {
    title: "AI管理",
    icon: "Cpu",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN"],
    children: [
      { title: "智能体广场", path: "/ai/agent-marketplace" },
      { title: "顾问规则", path: "/advisor/rules" },
      { title: "AI媒体处理", path: "/ai/media-processing" },
      { title: "对话日志", path: "/ai/chat-logs" },
      { title: "调用监控", path: "/ai/call-monitor" },
      { title: "圈主助理", path: "/ai/circle-assistants" },
      { title: "知识库管理", path: "/knowledge" },
      { title: "AI内容生成", path: "/content-generation" },
      { title: "AI运营追踪", path: "/ai/operation-dashboard" },
      { title: "RAG模板管理", path: "/ai/rag-templates" },
      { title: "智能客服", path: "/ai/customer-service", roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "CUSTOMER_SERVICE"] },
      { title: "AI内容质量", path: "/ai/content-quality", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "AI模型路由", path: "/system/ai-gateway", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "AI数据探索", path: "/ai/data-explorer", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "AI异常检测", path: "/ai/anomaly-detector", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "AI协作审核", path: "/ai/collaborations", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
    ],
  },
  {
    title: "管理驾驶舱",
    icon: "Odometer",
    path: "/admin/cockpit",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN"],
  },
  {
    title: "对外大屏",
    icon: "Monitor",
    roles: ALL_ADMIN,
    children: [
      { title: "平台综合大屏", path: "/bigscreen/platform" },
      { title: "实时交易大屏", path: "/bigscreen/transactions" },
      { title: "内容生态大屏", path: "/bigscreen/content-eco" },
      { title: "AI能力大屏", path: "/bigscreen/ai-capability" },
      { title: "线下驿站大屏", path: "/bigscreen/offline-map" },
      { title: "Token管理", path: "/admin/bigscreen-tokens", roles: ["SUPER_ADMIN"] },
    ],
  },
  {
    title: "数据看板",
    icon: "DataAnalysis",
    roles: ALL_ADMIN,
    children: [
      { title: "运营看板", path: "/dashboard/overview", roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "FINANCE_ADMIN"] },
      { title: "转化漏斗", path: "/dashboard/funnels", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "性能观测", path: "/dashboard/perf", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "用户标签", path: "/user-tags", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "平台总览", path: "/data/platform" },
      { title: "圈子数据", path: "/data/circle" },
      { title: "课程数据", path: "/data/course" },
      { title: "直播数据", path: "/data/live" },
      { title: "分站数据", path: "/data/station", roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "FINANCE_ADMIN"] },
    ],
  },
  {
    title: "线下管理",
    icon: "OfficeBuilding",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN"],
    children: [
      { title: "分站管理", path: "/stations" },
      { title: "线下驿站", path: "/offline-venues" },
      { title: "线下课程", path: "/offline/courses" },
      { title: "驿站核销记录", path: "/offline/checkins" },
      { title: "驿站商品监控", path: "/offline/products" },
      { title: "师资预约监控", path: "/offline/bookings" },
    ],
  },
  {
    title: "通知管理",
    icon: "Bell",
    path: "/notifications",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "CUSTOMER_SERVICE"],
  },
  {
    title: "短信管理",
    icon: "Message",
    path: "/sms",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN"],
  },
  {
    title: "研究院管理",
    icon: "School",
    path: "/institutes",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN"],
  },
  {
    title: "举报管理",
    icon: "WarningFilled",
    path: "/reports",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "CUSTOMER_SERVICE"],
  },
  {
    title: "评论管理",
    icon: "ChatLineSquare",
    path: "/comments",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "CONTENT_AUDITOR"],
  },
  {
    title: "互动数据",
    icon: "TrendCharts",
    path: "/interactions",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "CONTENT_AUDITOR"],
  },
  {
    title: "自动化运营",
    icon: "Robot",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN"],
    children: [
      { title: "任务池", path: "/operation/tasks" },
      { title: "运营引擎", path: "/operation/engine" },
      { title: "运营机器人", path: "/operation/robots" },
    ],
  },
  {
    title: "搜索分析",
    icon: "Search",
    path: "/search-analytics",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN"],
  },
  {
    title: "IM管理",
    icon: "ChatDotSquare",
    path: "/im",
    roles: ["SUPER_ADMIN", "OPERATION_ADMIN"],
  },
  {
    title: "系统管理",
    icon: "Setting",
    roles: ["SUPER_ADMIN"],
    children: [
      { title: "Banner管理", path: "/banners" },
      { title: "系统设置", path: "/system-settings" },
      { title: "敏感词管理", path: "/system/sensitive-words" },
      { title: "合规扫描", path: "/system/compliance-scan", roles: ["SUPER_ADMIN", "OPERATION_ADMIN", "CONTENT_AUDITOR"] },
      { title: "任务池", path: "/system/ops-tasks", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "Webhook管理", path: "/system/webhooks" },
      { title: "数据导入", path: "/system/import" },
      { title: "邮件管理", path: "/system/email", roles: ["SUPER_ADMIN"] },
      { title: "虚拟币配置", path: "/system/coin-config" },
      { title: "会员配置", path: "/system/member-config" },
      { title: "运营商等级", path: "/system/operator-level" },
      { title: "角色权限", path: "/system/role-permission" },
      { title: "功能开关", path: "/system/feature-flags" },
      { title: "第三方配置", path: "/system/third-party" },
      { title: "品牌配置", path: "/system/brand" },
      { title: "操作日志", path: "/system/operation-logs" },
      { title: "配置版本", path: "/system/config-versions" },
      { title: "审计日志", path: "/audit-logs" },
      { title: "错误监控", path: "/system/error-monitor", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "搜索权重", path: "/system/search-weights" },
      { title: "首页模块配置", path: "/system/homepage-config", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "全站公告", path: "/system/site-notices", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "用户协议", path: "/system/legal-documents", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
      { title: "APP版本", path: "/system/app-versions", roles: ["SUPER_ADMIN", "OPERATION_ADMIN"] },
    ],
  },
];
