<template>
  <view class="page"><view class="nav"><text class="nb" @click="goBack">←</text><text class="nt">签到管理</text><view style="width:48rpx"/></view>
    <view class="c"><view class="card"><text class="ct">{{course.title}}</text><text class="cm">{{course.students}}名学员</text></view>
    <view class="card"><text class="ct">今日签到</text><text class="cn">{{todaySigned}}/{{course.students}} 已签到</text>
      <view class="cb"><view class="cbf" :style="{width:(todaySigned/course.students*100)+'%'}"/></view></view>
    <view class="card"><text class="ct">签到记录</text><view v-for="r in records" :key="r.id" class="cr"><text class="cra">{{r.name[0]}}</text><view><text class="crn">{{r.name}}</text><text class="crt">{{r.time}}</text></view><text :class="r.status==='signed'?'up':'down'">{{r.status==='signed'?'✓已签':'未签'}}</text></view></view></view></view>
</template>
<script setup lang="ts">import {ref} from 'vue';const todaySigned=23;const course={title:'八字命理入门班',students:32};const records=ref([{id:1,name:'张三',time:'14:30',status:'signed'},{id:2,name:'李四',time:'14:35',status:'signed'},{id:3,name:'王五',status:'unsigned'}]);function goBack(){uni.navigateBack()}</script>
<style scoped>.page{background:#FAF8F5;min-height:100vh}.nav{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:56px;background:#fff;border-bottom:1px solid #E8E0D5}.nb{font-size:36rpx;color:#2C2C2C}.nt{font-size:32rpx;font-weight:600}.c{padding:24rpx}.card{background:#fff;border-radius:20rpx;padding:24rpx;margin-bottom:20rpx;box-shadow:0 2rpx 12rpx rgba(0,0,0,.04)}.ct{font-size:28rpx;font-weight:600;color:#2C2C2C;margin-bottom:12rpx;display:block}.cm{font-size:24rpx;color:#999}.cn{font-size:30rpx;font-weight:700;color:#C41E3A;display:block;margin-bottom:12rpx}.cb{height:12rpx;background:#F5F1EB;border-radius:6rpx;overflow:hidden}.cbf{height:100%;background:linear-gradient(90deg,#C41E3A,#E85A71);border-radius:6rpx}.cr{display:flex;align-items:center;gap:12rpx;padding:16rpx 0;border-bottom:1px solid #F5F1EB}.cra{width:56rpx;height:56rpx;border-radius:50%;background:#F5F1EB;display:flex;align-items:center;justify-content:center;font-size:24rpx;color:#999}.crn{font-size:26rpx;font-weight:500;color:#2C2C2C;display:block}.crt{font-size:20rpx;color:#999}.up{color:#22c55e;margin-left:auto}.down{color:#999;margin-left:auto}
</style>
