#!/usr/bin/env bash
set -euo pipefail

# Generated by env-setup skill
# Platform: <detected platform>
# Date: <timestamp>

echo "=== Project Setup ==="

# Check prerequisites
command -v node >/dev/null 2>&1 || { echo "Node.js is required. Install via: <platform-specific command>"; exit 1; }
# ... more checks ...

# Install dependencies
npm ci

# Setup environment
if [ ! -f .env ]; then
  cp .env.example .env
  echo "Created .env from .env.example - fill in secret values"
fi

# Start services
docker compose up -d

# Run migrations
npm run db:migrate  # if applicable

# Verify
npm run build
echo "=== Setup complete ==="
