<template>
  <view class="page"><view class="nav"><text class="nb" @click="goBack">←</text><text class="nt">限时秒杀</text><view style="width:48rpx"/></view>
    <view class="header"><text class="ht">⏰ 限时抢购</text><view class="cd"><text v-for="(v,i) in cds" :key="i" class="cdi"><text class="cdn">{{v}}</text><text class="cdl">{{labels[i]}}</text></text></view></view>
    <scroll-view scroll-y class="c"><view v-for="p in ps" :key="p.id" class="card">
      <view class="cc">🛍️</view><view class="ci"><text class="cn">{{p.name}}</text><view class="cp-row"><text class="cp">¥{{p.price}}</text><text class="co">¥{{p.orig}}</text></view>
        <view class="cb"><view class="cbf" :style="{width:(p.sold/p.total*100)+'%'}"/><text>{{p.sold}}/{{p.total}}</text></view></view>
      <view class="cbtn" @click="buy">抢购</view></view><view style="height:48rpx"/></scroll-view></view>
</template>
<script setup lang="ts">import {ref} from 'vue';const cds=ref(['02','30','45']);const labels=['时','分','秒'];const ps=ref([{id:1,name:'渊海子平精装版',price:58,orig:98,sold:85,total:100},{id:2,name:'专业罗盘',price:198,orig:398,sold:42,total:50}]);function buy(){uni.navigateTo({url:'/pages/shop/product-detail/index'})};function goBack(){uni.navigateBack()}</script>
<style scoped>.page{background:#FAF8F5;min-height:100vh}.nav{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:56px;background:#fff;border-bottom:1px solid #E8E0D5}.nb{font-size:36rpx;color:#2C2C2C}.nt{font-size:32rpx;font-weight:600}.header{background:linear-gradient(90deg,#C41E3A,#E74C3C);padding:32rpx;text-align:center;color:#fff}.ht{font-size:28rpx;display:block;margin-bottom:20rpx}.cd{display:flex;justify-content:center;gap:24rpx}.cdi{text-align:center}.cdn{font-size:48rpx;font-weight:900;display:block;background:rgba(0,0,0,.2);padding:12rpx 20rpx;border-radius:12rpx}.cdl{font-size:22rpx;opacity:.8;margin-top:4rpx}.c{padding:24rpx}.card{display:flex;align-items:center;gap:16rpx;background:#fff;border-radius:16rpx;padding:20rpx;margin-bottom:12rpx;box-shadow:0 2rpx 8rpx rgba(0,0,0,.03)}.cc{width:100rpx;height:100rpx;border-radius:12rpx;background:#F5F1EB;display:flex;align-items:center;justify-content:center;font-size:48rpx;flex-shrink:0}.cn{font-size:26rpx;font-weight:500;color:#2C2C2C;display:block}.cp-row{display:flex;align-items:baseline;gap:12rpx;margin-top:6rpx}.cp{font-size:28rpx;font-weight:700;color:#C41E3A}.co{font-size:22rpx;color:#999;text-decoration:line-through}.cb{flex:1;height:8rpx;background:#F5F1EB;border-radius:4rpx;overflow:hidden;margin-top:8rpx;display:flex;align-items:center;gap:8rpx;font-size:20rpx;color:#999}.cbf{height:100%;background:linear-gradient(90deg,#C41E3A,#E74C3C);border-radius:4rpx}.cbtn{padding:14rpx 28rpx;background:linear-gradient(90deg,#C41E3A,#E74C3C);color:#fff;border-radius:40rpx;font-size:24rpx}
</style>
