-- Video: 新增互动计数
ALTER TABLE "Video" ADD COLUMN "commentCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Video" ADD COLUMN "shareCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Video" ADD COLUMN "collectCount" INTEGER NOT NULL DEFAULT 0;
