<template>
  <view class="page">
    <view class="stream-area"><view class="sa-main"><text class="sam-icon">▶</text></view>
      <view class="sa-top"><text class="sat-host">{{live.host}}·👁️{{live.viewers}}</text><text class="sat-close" @click="goBack">✕</text></view>
      <view class="sa-right"><view class="sar-btn" @click="toggleLike"><text>❤️</text><text class="sar-count">{{likes}}</text></view><view class="sar-btn"><text>💬</text></view><view class="sar-btn"><text>🎁</text></view></view>
    </view>

    <view class="danmaku"><view v-for="d in danmaku" :key="d.id" class="dm-item"><text class="dmi-user">{{d.user}}: </text><text>{{d.content}}</text></view></view>

    <view v-if="product" class="product-float" @click="showProduct=true"><text class="pf-img">🛍️</text><view><text class="pf-name">{{product.name}}</text><text class="pf-price">¥{{product.price}}</text></view></view>

    <view class="bottom-bar"><input class="bb-input" placeholder="说点什么..."/><view class="bb-icons"><text @click="toggleLike">❤️</text><text>🎁</text><text>🛍️</text></view></view>

    <view v-if="showProduct" class="product-sheet" @click="showProduct=false"><view class="ps-card" @click.stop><text class="ps-title">{{product.name}}</text><text class="ps-price">¥{{product.price}}</text><view class="ps-btn">立即购买</view></view></view>
  </view>
</template>
<script setup lang="ts">import {ref} from 'vue';import {onPullDownRefresh} from '@dcloudio/uni-app';const likes=ref(12800),showProduct=ref(false);const live={host:'周易大师',viewers:'1,258'};const danmaku=ref([{id:1,user:'易学小白',content:'老师讲得真好！'},{id:2,user:'命理爱好者',content:'请问怎么看财运？'},{id:3,user:'风水先生',content:'支持老师！'},{id:4,user:'紫微迷',content:'能讲讲紫微斗数吗？'}]);const product={name:'八字命理精讲课程',price:199};function toggleLike(){likes.value++};function goBack(){uni.navigateBack()};onPullDownRefresh(()=>setTimeout(()=>uni.stopPullDownRefresh(),500))</script>
<style scoped>.page{background:#000;min-height:100vh;position:relative}.stream-area{position:relative;height:100vh}.sa-main{width:100%;height:100%;background:#1a1a2e;display:flex;align-items:center;justify-content:center}.sam-icon{font-size:80rpx;color:rgba(255,255,255,.3)}.sa-top{position:absolute;top:0;left:0;right:0;display:flex;justify-content:space-between;padding:24rpx 24rpx;background:linear-gradient(180deg,rgba(0,0,0,.6),transparent)}.sat-host{font-size:26rpx;color:#fff}.sat-close{font-size:32rpx;color:#fff;padding:8rpx}.sa-right{position:absolute;right:16rpx;top:50%;transform:translateY(-50%);display:flex;flex-direction:column;align-items:center;gap:24rpx;color:#fff;font-size:36rpx}.sar-btn{display:flex;flex-direction:column;align-items:center;gap:4rpx}.sar-count{font-size:22rpx}.danmaku{position:absolute;left:16rpx;bottom:260rpx;right:120rpx;max-height:50%;overflow-y:auto}.dm-item{padding:4rpx 0;font-size:22rpx;color:#fff;text-shadow:0 1rpx 2rpx rgba(0,0,0,.5)}.dmi-user{color:#C9A96E}.product-float{position:absolute;bottom:160rpx;left:16rpx;display:flex;align-items:center;gap:12rpx;background:rgba(0,0,0,.7);border-radius:16rpx;padding:16rpx;color:#fff;z-index:5}.pf-img{font-size:36rpx}.pf-name{font-size:24rpx;display:block}.pf-price{font-size:28rpx;font-weight:600;color:#C41E3A}.bottom-bar{position:absolute;bottom:0;left:0;right:0;display:flex;align-items:center;gap:16rpx;padding:16rpx 24rpx 32rpx;background:rgba(0,0,0,.8)}.bb-input{flex:1;height:72rpx;background:rgba(255,255,255,.2);border-radius:40rpx;padding:0 24rpx;font-size:24rpx;color:#fff}.bb-icons{display:flex;gap:20rpx;font-size:32rpx;color:#fff}.product-sheet{position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:50;display:flex;align-items:flex-end}.ps-card{width:100%;background:#fff;border-radius:32rpx 32rpx 0 0;padding:32rpx 24rpx 48rpx;text-align:center}.ps-title{font-size:32rpx;font-weight:600;display:block}.ps-price{font-size:44rpx;font-weight:700;color:#C41E3A;display:block;margin:16rpx 0}.ps-btn{padding:28rpx;background:linear-gradient(90deg,#C41E3A,#E74C3C);color:#fff;border-radius:24rpx;font-size:28rpx;font-weight:600}
</style>
