<template>
  <view class="page"><view class="nav"><text class="nb" @click="goBack">←</text><text class="nt">{{expert.name}}</text><view style="width:48rpx"/></view>
    <view class="c"><view class="card"><text class="ha">{{expert.name[0]}}</text><text class="hn">{{expert.name}}</text><text class="ht">{{expert.title}}</text><text class="hd">{{expert.bio}}</text><view class="hs"><text>⭐{{expert.rating}}</text><text>{{expert.consults}}次咨询</text></view></view>
    <view class="card"><text class="ct">选择日期</text><view class="cal"><text class="cm">{{currMonth}}月</text><view class="cd"><text v-for="d in days" :key="d" class="cdi" :class="{s:selDay===d}" @click="selDay=d">{{d}}</text></view></view></view>
    <view class="card"><text class="ct">选择时间</text><view class="sl"><text v-for="s in slots" :key="s" class="si" :class="{s:selSlot===s}" @click="selSlot=s">{{s}}</text></view></view>
    <view class="card"><text class="ct">费用</text><text class="price">¥{{expert.price}}<text class="pu">/次</text></text></view>
    <view class="btn" @click="book">确认预约</view></view></view>
</template>
<script setup lang="ts">import {ref} from 'vue';const currMonth=ref(5),selDay=ref(15),selSlot=ref('');const expert={name:'周易大师',title:'资深命理师',bio:'从业20年',rating:4.9,consults:3680,price:500};const days=[12,13,14,15,16,17,18];const slots=['09:00','10:00','11:00','14:00','15:00','16:00'];function book(){uni.showToast({title:'预约成功'})};function goBack(){uni.navigateBack()}</script>
<style scoped>.page{background:#FAF8F5;min-height:100vh}.nav{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:56px;background:#fff;border-bottom:1px solid #E8E0D5}.nb{font-size:36rpx;color:#2C2C2C}.nt{font-size:32rpx;font-weight:600}.c{padding:24rpx}.card{background:#fff;border-radius:20rpx;padding:24rpx;margin-bottom:20rpx;box-shadow:0 2rpx 12rpx rgba(0,0,0,.04);text-align:center}.ha{width:120rpx;height:120rpx;border-radius:50%;background:rgba(196,30,58,.1);display:flex;align-items:center;justify-content:center;font-size:48rpx;color:#C41E3A;margin:0 auto 12rpx}.hn{font-size:34rpx;font-weight:600;color:#2C2C2C;display:block}.ht{font-size:24rpx;color:#999;margin:6rpx 0}.hd{font-size:24rpx;color:#666;margin-bottom:12rpx}.hs{font-size:22rpx;color:#999}.ct{font-size:28rpx;font-weight:600;color:#2C2C2C;margin-bottom:16rpx;display:block;text-align:left}.cm{font-size:30rpx;font-weight:600;color:#2C2C2C;display:block;margin-bottom:12rpx}.cd{display:flex;gap:12rpx;justify-content:center}.cdi{width:72rpx;height:72rpx;border-radius:50%;display:flex;align-items:center;justify-content:center;background:#F5F1EB;font-size:26rpx;color:#666}.cdi.s{background:#C41E3A;color:#fff}.sl{display:flex;flex-wrap:wrap;gap:12rpx;justify-content:center}.si{padding:16rpx 32rpx;background:#F5F1EB;border-radius:40rpx;font-size:24rpx;color:#666}.si.s{background:#C41E3A;color:#fff}.price{font-size:48rpx;font-weight:700;color:#C41E3A}.pu{font-size:24rpx;color:#999}.btn{padding:28rpx;text-align:center;background:linear-gradient(90deg,#C41E3A,#E74C3C);color:#fff;border-radius:24rpx;font-size:28rpx;font-weight:600}
</style>
