import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {randomBytes} from 'node:crypto';
import {loadCandidatePrisma} from '../../scripts/ops/prisma-candidate/client.mjs';
const repo=fileURLToPath(new URL('../../',import.meta.url));const require=createRequire(resolve(repo,'apps/server/package.json'));const adminRequire=createRequire(resolve(repo,'apps/admin/package.json'));
const {PrismaClient}=loadCandidatePrisma();require('ts-node').register({transpileOnly:true,compilerOptions:{module:'commonjs',experimentalDecorators:true,emitDecoratorMetadata:true}});require('reflect-metadata');
const password=JSON.parse(readFileSync(resolve(repo,'pilots/managed-tenancy/.runtime/postgres/synthetic-connections.json'),'utf8')).mt_control;
const db=new PrismaClient({datasources:{db:{url:`postgresql://mt_control:${password}@127.0.0.1:55467/mt_control`}}});
const identity=await db.$queryRawUnsafe('SELECT current_database() db,current_user actor,inet_server_port() port');if(identity[0].db!=='mt_control'||identity[0].actor!=='mt_control'||identity[0].port!==55467)throw new Error('只允许本任务合成库');
const {Global,Module}=require('@nestjs/common');const {Test}=require('@nestjs/testing');const {PassportModule}=require('@nestjs/passport');
const {PrismaService}=require(resolve(repo,'apps/server/src/prisma/prisma.service.ts'));const {RedisService}=require(resolve(repo,'apps/server/src/redis/redis.service.ts'));const {JwtStrategy}=require(resolve(repo,'apps/server/src/common/jwt.strategy.ts'));const {ManagedTenancyModule}=require(resolve(repo,'apps/server/src/modules/managed-tenancy/managed-tenancy.module.ts'));
const secret=randomBytes(32).toString('hex');process.env.JWT_SECRET=secret;const user=await db.user.create({data:{nickname:'本任务页面合成维护员',roles:{create:{roleType:'SUPER_ADMIN'}}}});const jwt=require('jsonwebtoken');
class FixtureDatabase{}Global()(FixtureDatabase);Module({providers:[{provide:PrismaService,useValue:db},{provide:RedisService,useValue:{get:async()=>null}}],exports:[PrismaService,RedisService]})(FixtureDatabase);
const testing=await Test.createTestingModule({imports:[FixtureDatabase,PassportModule.register({defaultStrategy:'jwt'}),ManagedTenancyModule],providers:[JwtStrategy]}).compile();const app=testing.createNestApplication();app.setGlobalPrefix('api/v1');
app.getHttpAdapter().getInstance().get('/__fixture/auth',(_req,res)=>res.set('Cache-Control','no-store').json({token:jwt.sign({sub:user.id,sessionIssuedAt:Date.now()},secret,{expiresIn:'30m'})}));
await app.listen(0,'127.0.0.1');const apiPort=app.getHttpServer().address().port;
const {createServer,loadConfigFromFile}=await import(pathToFileURL(adminRequire.resolve('vite')).href);
const loaded=await loadConfigFromFile({command:'build',mode:'development'},resolve(repo,'apps/admin/vite.config.ts'));
const previewId='virtual:managed-preview';const virtualId='\0'+previewId;
const plugin={name:'managed-preview-only',resolveId(id){if(id===previewId)return virtualId;},load(id){if(id===virtualId)return `import {createApp,h} from 'vue';import ElementPlus from 'element-plus';import 'element-plus/dist/index.css';import '@/styles/tokens.css';import '@/styles/global.css';import Managed from '@/views/tenant/ManagedCustomerList.vue';const auth=await fetch('/__fixture/auth').then(r=>r.json());localStorage.setItem('token',auth.token);createApp({render:()=>h(Managed)}).use(ElementPlus).mount('#app');`;},configureServer(server){server.middlewares.use(async(req,res,next)=>{if(req.url?.split('?')[0]!=='/tenant-preview')return next();const html=await server.transformIndexHtml('/tenant-preview',`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>托管客户候选验收 · 本机合成数据</title><div id="app"></div><script type="module" src="/@id/${previewId}"></script></html>`);res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html);});}};
const vite=await createServer({...loaded.config,configFile:false,root:resolve(repo,'apps/admin'),base:'/',plugins:[...loaded.config.plugins,plugin],server:{host:'127.0.0.1',port:0,strictPort:true,fs:{deny:['.env','.env.*','**/.runtime/**','**/*credentials*.json']},proxy:{'/api':{target:`http://127.0.0.1:${apiPort}`,changeOrigin:true},'/__fixture':{target:`http://127.0.0.1:${apiPort}`,changeOrigin:true}}}});await vite.listen();const uiPort=vite.httpServer.address().port;
console.log(JSON.stringify({ui:`http://127.0.0.1:${uiPort}/tenant-preview`,apiPort,production:false}));
process.stdin.resume();process.stdin.on('data',async data=>{if(data.toString().trim()==='stop'){await vite.close();await app.close();await db.$disconnect();process.exit(0);}});
