<template>
  <view class="page"><view class="nav"><text class="nb" @click="goBack">←</text><text class="nt">帖子详情</text><view style="width:48rpx"/></view>
    <scroll-view scroll-y class="c" :style="{height:'calc(100vh - 56px - 120rpx)'}">
      <view class="card"><view class="ch"><text class="ca">{{post.author[0]}}</text><view><text class="cn">{{post.author}}</text><text class="ct">{{post.time}}</text></view></view>
        <text class="cc">{{post.content}}</text>
        <view class="cf"><text>❤️{{post.likes}}</text><text>💬{{post.comments.length}}</text></view></view>
      <view class="card"><text class="ct">评论({{post.comments.length}})</text>
        <view v-for="c in post.comments" :key="c.id" class="cmt"><text class="cma">{{c.user[0]}}</text><view><text class="cmn">{{c.user}}</text><text class="cmm">{{c.content}}</text></view></view></view><view style="height:48rpx"/></scroll-view>
    <view class="bb"><input class="bbi" placeholder="写评论..."/><text class="bbs">发送</text></view></view>
</template>
<script setup lang="ts">import {ref} from 'vue';const post=ref({author:'周易大师',time:'3天前',content:'今天分享一个八字看财运的心得：日主身旺财星有根，大运流年再遇财星必有进财之喜。',likes:328,comments:[{id:1,user:'易学爱好者',content:'讲得很清晰！'},{id:2,user:'命理新手',content:'受益匪浅，谢谢老师'}]});function goBack(){uni.navigateBack()}</script>
<style scoped>.page{background:#FAF8F5;min-height:100vh}.nav{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:56px;background:#fff;border-bottom:1px solid #E8E0D5}.nb{font-size:36rpx;color:#2C2C2C}.nt{font-size:32rpx;font-weight:600}.c{padding:24rpx}.card{background:#fff;border-radius:20rpx;padding:24rpx;margin-bottom:16rpx;box-shadow:0 2rpx 12rpx rgba(0,0,0,.04)}.ch{display:flex;align-items:center;gap:12rpx;margin-bottom:16rpx}.ca{width:56rpx;height:56rpx;border-radius:50%;background:#F5F1EB;display:flex;align-items:center;justify-content:center;font-size:24rpx;color:#999}.cn{font-size:26rpx;font-weight:500;color:#2C2C2C;display:block}.ct{font-size:22rpx;color:#999}.cc{font-size:26rpx;color:#333;line-height:1.6;margin-bottom:16rpx}.cf{display:flex;gap:32rpx;font-size:22rpx;color:#999}.cmt{display:flex;gap:12rpx;padding:16rpx 0;border-bottom:1px solid #F5F1EB}.cma{width:48rpx;height:48rpx;border-radius:50%;background:#F5F1EB;display:flex;align-items:center;justify-content:center;font-size:20rpx;color:#999;flex-shrink:0}.cmn{font-size:24rpx;font-weight:500;color:#2C2C2C;display:block}.cmm{font-size:24rpx;color:#666;margin-top:4rpx}.bb{position:fixed;bottom:0;left:0;right:0;display:flex;align-items:center;gap:16rpx;padding:16rpx 24rpx;background:#fff;border-top:1px solid #E8E0D5}.bbi{flex:1;height:72rpx;background:#F5F1EB;border-radius:40rpx;padding:0 24rpx;font-size:26rpx}.bbs{padding:14rpx 28rpx;background:#C41E3A;color:#fff;border-radius:40rpx;font-size:26rpx}
</style>
