# .circleci/config.yml
version: 2.1
orbs:
  node: circleci/node@5
jobs:
  test:
    docker:
      - image: cimg/node:20.0
      - image: cimg/postgres:15.0
    steps:
      - checkout
      - node/install-packages
      - run: npm test
      - store_test_results:
          path: test-results
  deploy:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - run: npm run deploy
workflows:
  build-and-deploy:
    jobs:
      - test
      - deploy:
          requires: [test]
          filters:
            branches:
              only: main
