<template>
  <view class="page"><view class="nav"><text class="nb" @click="goBack">←</text><text class="nt">购物车</text><text class="ne" @click="edit=!edit">{{edit?'完成':'编辑'}}</text></view>
    <scroll-view scroll-y class="c" :style="{height:'calc(100vh - 56px - 140rpx)'}">
      <view v-for="item in items" :key="item.id" class="card">
        <checkbox :checked="item.sel" @change="item.sel=!item.sel" v-if="!edit"/>
        <view class="cc">🛍️</view>
        <view class="ci"><text class="cin">{{item.name}}</text><text class="cs">{{item.sku}}</text><view class="cb"><text class="cprice">¥{{item.price}}</text><view class="cqty"><text @click="item.qty>1&&item.qty--">-</text><text>{{item.qty}}</text><text @click="item.qty++">+</text></view></view></view>
        <text v-if="edit" class="del" @click="del(item.id)">🗑️</text>
      </view>
      <view v-if="items.length===0" class="em">🛒 购物车是空的</view><view style="height:48rpx"/></scroll-view>
    <view class="bb"><view class="bb-total">合计 ¥{{total}}</view><view class="bb-btn" @click="checkout">结算({{selCount}})</view></view>
  </view>
</template>
<script setup lang="ts">import {ref,computed} from 'vue';import {onPullDownRefresh} from '@dcloudio/uni-app';const edit=ref(false);const items=ref([{id:1,name:'渊海子平精装版',sku:'平装版',price:98,qty:1,sel:true},{id:2,name:'专业罗盘',sku:'标准版',price:398,qty:1,sel:true}]);const total=computed(()=>items.value.filter(i=>i.sel).reduce((s,i)=>s+i.price*i.qty,0));const selCount=computed(()=>items.value.filter(i=>i.sel).reduce((s,i)=>s+i.qty,0));function del(id:number){items.value=items.value.filter(i=>i.id!==id)};function checkout(){uni.navigateTo({url:'/pages/shop/checkout/index'})};function goBack(){uni.navigateBack()};onPullDownRefresh(()=>setTimeout(()=>uni.stopPullDownRefresh(),500))</script>
<style scoped>.page{background:#FAF8F5;min-height:100vh}.nav{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:56px;background:#fff;border-bottom:1px solid #E8E0D5}.nb{font-size:36rpx;color:#2C2C2C}.nt{font-size:32rpx;font-weight:600}.ne{font-size:24rpx;color:#C41E3A}.c{padding:24rpx}.card{display:flex;align-items:center;gap:16rpx;background:#fff;border-radius:16rpx;padding:24rpx;margin-bottom:12rpx;box-shadow:0 2rpx 8rpx rgba(0,0,0,.03)}.cc{width:88rpx;height:88rpx;border-radius:12rpx;background:#F5F1EB;display:flex;align-items:center;justify-content:center;font-size:40rpx;flex-shrink:0}.cin{font-size:26rpx;color:#2C2C2C;display:block}.cs{font-size:22rpx;color:#999}.cb{display:flex;justify-content:space-between;align-items:center;margin-top:8rpx}.cprice{font-size:26rpx;font-weight:500;color:#C41E3A}.cqty{display:flex;align-items:center;gap:16rpx}.cqty text{padding:4rpx 16rpx;border:1px solid #E8E0D5;border-radius:8rpx;font-size:24rpx}.del{font-size:32rpx;color:#ef4444}.em{padding:160rpx 0;text-align:center;font-size:26rpx;color:#999}.bb{position:fixed;bottom:0;left:0;right:0;display:flex;align-items:center;gap:24rpx;padding:20rpx 24rpx;background:#fff;border-top:1px solid #E8E0D5;z-index:50}.bb-total{flex:1;font-size:32rpx;font-weight:700;color:#C41E3A}.bb-btn{padding:24rpx 56rpx;background:linear-gradient(90deg,#C41E3A,#E74C3C);color:#fff;border-radius:40rpx;font-size:28rpx;font-weight:600}
</style>
