<template>
  <view class="page"><view class="nav"><text class="nb" @click="goBack">←</text><text class="nt">商品分类</text><text class="ns" @click="goSearch">🔍</text></view>
    <view class="body"><scroll-view scroll-y class="left"><view v-for="c in cats" :key="c.id" class="li" :class="{a:sel===c.id}" @click="sel=c.id"><text>{{c.name}}</text></view></scroll-view>
      <scroll-view scroll-y class="right" v-if="cur"><view class="sub"><text v-for="s in cur.sub" :key="s" class="st">{{s}}</text></view>
        <view class="grid"><view v-for="p in cur.ps" :key="p.id" class="gi"><view class="gc">🛍️</view><text class="gn">{{p.name}}</text><text class="gp">¥{{p.price}}</text></view></view></scroll-view></view>
  </view>
</template>
<script setup lang="ts">import {ref,computed} from 'vue';import {onPullDownRefresh} from '@dcloudio/uni-app';const sel=ref(1);const cats=ref([{id:1,name:'全部',sub:['热门','新品'],ps:[{id:1,name:'渊海子平',price:98},{id:2,name:'专业罗盘',price:398},{id:3,name:'五帝钱',price:88}]},{id:2,name:'书籍',sub:['经典','入门'],ps:[{id:4,name:'八字入门',price:68}]},{id:3,name:'文创',sub:['摆件','文房'],ps:[{id:5,name:'开光貔貅',price:168}]}]);const cur=computed(()=>cats.value.find(c=>c.id===sel.value));function goSearch(){};function goBack(){uni.navigateBack()};onPullDownRefresh(()=>setTimeout(()=>uni.stopPullDownRefresh(),500))</script>
<style scoped>.page{background:#FAF8F5;min-height:100vh}.nav{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:56px;background:#fff;border-bottom:1px solid #E8E0D5}.nb{font-size:36rpx;color:#2C2C2C}.nt{font-size:32rpx;font-weight:600}.ns{font-size:32rpx}.body{display:flex;height:calc(100vh - 56px)}.left{width:200rpx;background:#fff;border-right:1px solid #E8E0D5}.li{padding:28rpx 24rpx;font-size:26rpx;color:#999;border-left:4rpx solid transparent}.li.a{color:#C41E3A;font-weight:500;border-left-color:#C41E3A;background:#FFF5F5}.right{flex:1;padding:20rpx}.sub{display:flex;gap:8rpx;margin-bottom:16rpx}.st{padding:8rpx 16rpx;background:#F5F1EB;border-radius:20rpx;font-size:20rpx;color:#999}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12rpx}.gi{background:#fff;border-radius:12rpx;overflow:hidden;box-shadow:0 2rpx 8rpx rgba(0,0,0,.03)}.gc{aspect-ratio:1;background:#F5F1EB;display:flex;align-items:center;justify-content:center;font-size:48rpx}.gn{font-size:24rpx;color:#2C2C2C;padding:8rpx 12rpx 0}.gp{font-size:26rpx;font-weight:600;color:#C41E3A;padding:6rpx 12rpx 12rpx}
</style>
