<template>
  <view class="page"><view class="nav"><text class="nb" @click="goBack">←</text><text class="nt">商品详情</text><text class="ns" @click="share">📤</text></view>
    <scroll-view scroll-y class="c" :style="{height:'calc(100vh - 56px - 120rpx)'}">
      <view class="ga"><view class="gm">🛍️</view></view>
      <view class="info"><text class="in">{{p.name}}</text><view class="ipr"><text class="ip">¥{{p.price}}</text><text class="io">¥{{p.orig}}</text><text class="is">已售{{p.sold}}</text></view></view>
      <view class="card"><text class="ct">规格选择</text><view class="sk"><text v-for="s in p.skus" :key="s.id" class="sk" :class="{a:sk===s.id}" @click="sk=s.id">{{s.name}}</text></view></view>
      <view class="card"><text class="ct">商品详情</text><text class="desc">{{p.desc}}</text></view><view style="height:48rpx"/></scroll-view>
    <view class="bb"><view class="bbc" @click="addCart">🛒</view><view class="bbb" @click="buyNow">立即购买</view></view>
  </view>
</template>
<script setup lang="ts">import {ref} from 'vue';const sk=ref(1);const p=ref({name:'渊海子平精装版',price:98,orig:168,sold:256,desc:'《渊海子平》是八字命理学的经典著作。',skus:[{id:1,name:'平装版¥98'},{id:2,name:'精装版¥128'}]});function addCart(){uni.showToast({title:'已加入购物车'})};function buyNow(){uni.navigateTo({url:'/pages/shop/checkout/index'})};function share(){};function goBack(){uni.navigateBack()}</script>
<style scoped>.page{background:#FAF8F5;min-height:100vh}.nav{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:56px;background:#fff;border-bottom:1px solid #E8E0D5}.nb{font-size:36rpx;color:#2C2C2C}.nt{font-size:32rpx;font-weight:600}.ns{font-size:32rpx}.c{}.ga{}.gm{aspect-ratio:1;background:#F5F1EB;display:flex;align-items:center;justify-content:center;font-size:120rpx}.info{background:#fff;padding:24rpx;margin-bottom:16rpx}.in{font-size:34rpx;font-weight:600;color:#2C2C2C;display:block;margin-bottom:16rpx}.ipr{display:flex;align-items:baseline;gap:12rpx}.ip{font-size:44rpx;font-weight:700;color:#C41E3A}.io{font-size:26rpx;color:#999;text-decoration:line-through}.is{font-size:22rpx;color:#999;margin-left:auto}.card{background:#fff;padding:24rpx;margin-bottom:16rpx}.ct{font-size:28rpx;font-weight:600;color:#2C2C2C;margin-bottom:16rpx;display:block}.sk{padding:14rpx 24rpx;background:#F5F1EB;border-radius:16rpx;font-size:24rpx;color:#999;display:inline-block;margin-right:12rpx}.sk.a{border:2rpx solid #C41E3A;color:#C41E3A;background:#FFF5F5}.desc{font-size:26rpx;color:#666;line-height:1.6}.bb{position:fixed;bottom:0;left:0;right:0;display:flex;align-items:center;gap:24rpx;padding:16rpx 24rpx;background:#fff;border-top:1px solid #E8E0D5;z-index:50}.bbc{font-size:44rpx;padding:8rpx}.bbb{flex:1;padding:28rpx;text-align:center;background:linear-gradient(90deg,#C41E3A,#E74C3C);color:#fff;border-radius:40rpx;font-size:28rpx;font-weight:600}
</style>
