-- 合-P1 合规违禁词库首版种子（2026-07-05）
-- 真源：docs/design/合规违禁词库-首版-20260704.md（F2 话术定性 + R1 传销表述 + R4 类目合规）
-- COMPLIANCE_A = 禁止（出现即报告·建议下架/拦截）；COMPLIANCE_B = 替换建议（replacement 为建议文案·人工确认）
-- 双属词（辟邪/开光/招财 在文档中 A/B 两见）按从严原则入 A 级，B 场景豁免边界写入 remark。
-- 幂等：ON CONFLICT ("word") 更新 category/replacement/remark，不覆盖 enabled（保留管理员手动禁用）。

INSERT INTO "SensitiveWord" ("word", "category", "replacement", "remark") VALUES
-- ── A 级 · 功效承诺类（R4 迷信定性风险）──
('改运',   'COMPLIANCE_A', NULL, '功效承诺类'),
('转运',   'COMPLIANCE_A', NULL, '功效承诺类'),
('化解',   'COMPLIANCE_A', NULL, '功效承诺类'),
('化太岁', 'COMPLIANCE_A', NULL, '功效承诺类'),
('破解',   'COMPLIANCE_A', NULL, '功效承诺类（技术语境"破解难题"误报由人工忽略）'),
('消灾',   'COMPLIANCE_A', NULL, '功效承诺类'),
('挡灾',   'COMPLIANCE_A', NULL, '功效承诺类'),
('避祸',   'COMPLIANCE_A', NULL, '功效承诺类'),
('辟邪',   'COMPLIANCE_A', NULL, '功效承诺禁止；商品描述场景建议替换为"传统纹样/民俗寓意平安"'),
('驱邪',   'COMPLIANCE_A', NULL, '功效承诺类'),
('镇宅',   'COMPLIANCE_A', NULL, '作功效承诺时禁止'),
('开光',   'COMPLIANCE_A', NULL, '功效承诺禁止；工艺描述"开光工艺"豁免（人工复核放行）'),
('加持',   'COMPLIANCE_A', NULL, '作功效承诺时禁止'),
('法事',   'COMPLIANCE_A', NULL, '功效承诺类'),
('做法',   'COMPLIANCE_A', NULL, '宗教仪式义禁止；日常"做法/方法"义误报由人工忽略'),
('符咒',   'COMPLIANCE_A', NULL, '功效承诺类'),
('画符',   'COMPLIANCE_A', NULL, '功效承诺类'),
('招财',   'COMPLIANCE_A', NULL, '承诺句式禁止；民俗寓意表述"寓意招财纳福"豁免'),
('旺财',   'COMPLIANCE_A', NULL, '功效承诺类'),
('催财',   'COMPLIANCE_A', NULL, '功效承诺类'),
('斩桃花', 'COMPLIANCE_A', NULL, '功效承诺类'),
('和合术', 'COMPLIANCE_A', NULL, '功效承诺类'),
('还阴债', 'COMPLIANCE_A', NULL, '功效承诺类'),
('超度',   'COMPLIANCE_A', NULL, '功效承诺类'),
('立杆见影', 'COMPLIANCE_A', NULL, '功效承诺类'),
('包灵验', 'COMPLIANCE_A', NULL, '功效承诺类'),
('百分百准', 'COMPLIANCE_A', NULL, '功效承诺类'),
('铁口直断', 'COMPLIANCE_A', NULL, '功效承诺类'),
-- ── A 级 · 确定性承诺类（价格法/广告法）──
('保证成功', 'COMPLIANCE_A', NULL, '确定性承诺类'),
('保证发财', 'COMPLIANCE_A', NULL, '确定性承诺类'),
('保证复合', 'COMPLIANCE_A', NULL, '确定性承诺类'),
('保证怀孕', 'COMPLIANCE_A', NULL, '确定性承诺类'),
('保证升官', 'COMPLIANCE_A', NULL, '确定性承诺类'),
('包好',   'COMPLIANCE_A', NULL, '确定性承诺类'),
('包中',   'COMPLIANCE_A', NULL, '确定性承诺类'),
('包过',   'COMPLIANCE_A', NULL, '确定性承诺类'),
('包准',   'COMPLIANCE_A', NULL, '确定性承诺类'),
('无效退款', 'COMPLIANCE_A', NULL, '未经法务的承诺'),
('稳赚',   'COMPLIANCE_A', NULL, '确定性承诺类'),
('必赚',   'COMPLIANCE_A', NULL, '确定性承诺类'),
('一定能', 'COMPLIANCE_A', NULL, '确定性承诺类'),
-- ── A 级 · 传销表述类（R1）──
('纯利润', 'COMPLIANCE_A', NULL, '传销表述类'),
('躺赚',   'COMPLIANCE_A', NULL, '传销表述类'),
('睡后收入', 'COMPLIANCE_A', NULL, '传销表述类'),
('拉人头', 'COMPLIANCE_A', NULL, '传销表述类'),
('人头费', 'COMPLIANCE_A', NULL, '传销表述类'),
('下线',   'COMPLIANCE_A', NULL, '作层级招募语禁止；"已下线/产品下线"等误报由人工忽略'),
('无限代', 'COMPLIANCE_A', NULL, '传销表述类'),
('层层返利', 'COMPLIANCE_A', NULL, '传销表述类'),
('永久归属', 'COMPLIANCE_A', NULL, '收益承诺语'),
('发展会员拿提成', 'COMPLIANCE_A', NULL, '传销表述类（句式）'),
-- ── A 级 · 医疗越界类 ──
('治病',   'COMPLIANCE_A', NULL, '医疗越界类'),
('治愈',   'COMPLIANCE_A', NULL, '医疗越界类'),
('疗效',   'COMPLIANCE_A', NULL, '医疗越界类'),
('根治',   'COMPLIANCE_A', NULL, '医疗越界类'),
('调理身体', 'COMPLIANCE_A', NULL, '作医疗承诺时禁止'),
-- ── B 级 · 替换建议（扫描报告给出替换·AI 生成时自动用替换词）──
('算命',   'COMPLIANCE_B', '命理文化分析', NULL),
('预测',   'COMPLIANCE_B', '推演参考 / 趋势分析', NULL),
('大师',   'COMPLIANCE_B', '老师 / 研究者 / 从业者', NULL),
('神算',   'COMPLIANCE_B', '资深研究者', NULL),
('半仙',   'COMPLIANCE_B', '资深研究者', NULL),
('风水宝地', 'COMPLIANCE_B', '环境格局上佳', '销售语从严'),
('开运',   'COMPLIANCE_B', '雅趣 / 祈愿 / 寓意吉祥', '商品名场景'),
('灵验',   'COMPLIANCE_B', '广受好评', NULL),
('命中注定', 'COMPLIANCE_B', '命理视角下的倾向', NULL),
('改命',   'COMPLIANCE_B', '认知自我、优化选择', NULL),
('占卜',   'COMPLIANCE_B', '民俗推演 / 传统文化体验', NULL)
ON CONFLICT ("word") DO UPDATE SET
  "category"    = EXCLUDED."category",
  "replacement" = EXCLUDED."replacement",
  "remark"      = EXCLUDED."remark",
  "updatedAt"   = CURRENT_TIMESTAMP;
