<template>
  <view class="page">
    <view class="nav"><text class="nav-back" @click="goBack">←</text><text class="nav-title">{{liveData.title}}</text><view style="width:48rpx"/></view>
    <view class="video-area"><view class="va-main"><text class="vam-icon">▶</text></view></view>
    <view class="tabs"><text v-for="t in tabs" :key="t.key" class="tab" :class="{act:activeTab===t.key}" @click="activeTab=t.key">{{t.label}}</text></view>
    <scroll-view v-if="activeTab==='slides'" scroll-y class="panel"><view v-for="s in slides" :key="s.id" class="slide-item"><text class="si-num">{{s.id}}</text><text class="si-title">{{s.title}}</text></view></scroll-view>
    <view v-if="activeTab==='qa'" class="panel">
      <view v-for="q in questions" :key="q.id" class="qa-item"><view class="qi-head"><text class="qi-status" :class="q.answered?'ok':'no'">{{q.answered?'已答':'待答'}}</text><text class="qi-user">{{q.user}}</text></view><text class="qi-content">{{q.content}}</text></view>
    </view>
    <view class="bb"><view class="bb-btn" @click="applyMic">🎤 申请连麦</view></view>
  </view>
</template>
<script setup lang="ts">import {ref} from 'vue';import {onPullDownRefresh} from '@dcloudio/uni-app';const activeTab=ref('slides');const liveData={title:'八字命理教学直播'};const tabs=[{key:'slides',label:'课件'},{key:'qa',label:'问答'}];const slides=[{id:1,title:'第一章：八字基础概念'},{id:2,title:'第二章：天干地支详解'},{id:3,title:'第三章：五行生克关系'}];const questions=[{id:1,user:'命理爱好者',content:'老师能讲讲食神和伤官的区别吗？',answered:true},{id:2,user:'风水新手',content:'日柱怎么排？',answered:false}];function applyMic(){uni.showToast({title:'连麦申请已发送',icon:'none'})};function goBack(){uni.navigateBack()};onPullDownRefresh(()=>setTimeout(()=>uni.stopPullDownRefresh(),500))</script>
<style scoped>.page{background:#000;min-height:100vh;display:flex;flex-direction:column}.nav{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:48px;background:rgba(0,0,0,.8)}.nav-back{font-size:28rpx;color:#fff}.nav-title{font-size:24rpx;color:#fff}.video-area{padding:12rpx;background:#1a1a2e}.va-main{aspect-ratio:16/9;background:#222;display:flex;align-items:center;justify-content:center;border-radius:8rpx}.vam-icon{font-size:60rpx;color:rgba(255,255,255,.3)}.tabs{display:flex;background:#111;border-bottom:1px solid #333}.tab{flex:1;text-align:center;padding:16rpx;font-size:24rpx;color:#999;border-bottom:2rpx solid transparent}.tab.act{color:#C41E3A;border-bottom-color:#C41E3A}.panel{flex:1;padding:24rpx;background:#FAF8F5}.slide-item{display:flex;align-items:center;gap:16rpx;padding:20rpx;background:#fff;border-radius:12rpx;margin-bottom:8rpx}.si-num{width:48rpx;height:48rpx;border-radius:50%;background:rgba(196,30,58,.1);display:flex;align-items:center;justify-content:center;font-weight:600;color:#C41E3A}.si-title{font-size:26rpx;color:#2C2C2C}.qa-item{background:#fff;border-radius:12rpx;padding:20rpx;margin-bottom:8rpx}.qi-head{display:flex;align-items:center;gap:8rpx;margin-bottom:8rpx}.qi-status{font-size:18rpx;padding:2rpx 10rpx;border-radius:6rpx}.qi-status.ok{background:rgba(34,197,94,.1);color:#22c55e}.qi-status.no{background:rgba(249,115,22,.1);color:#f97316}.qi-user{font-size:22rpx;color:#999}.qi-content{font-size:24rpx;color:#2C2C2C}.bb{padding:16rpx 24rpx;background:#fff;border-top:1px solid #E8E0D5}.bb-btn{padding:24rpx;text-align:center;background:#C41E3A;color:#fff;border-radius:24rpx;font-size:26rpx}
</style>
