<template>
  <view class="page">
    <view class="nav"><text class="nav-back" @click="goBack">←</text><view class="nav-group"><text class="ng-avatar">{{group.name[0]}}</text><text class="ng-name">{{group.name}}</text><text class="ng-count">{{group.members}}人</text></view><text class="nav-more" @click="goDetail">⋯</text></view>
    <scroll-view scroll-y class="msgs" :style="{height:'calc(100vh - 56px - 140rpx)'}">
      <view v-for="m in messages" :key="m.id" class="msg" :class="m.from==='me'?'right':'left'">
        <text v-if="m.from!=='me'" class="msg-avatar">{{m.user[0]}}</text>
        <view class="msg-body" :class="m.from==='me'?'mine':'other'"><text v-if="m.from!=='me'" class="mb-user">{{m.user}}</text><text class="mb-content">{{m.content}}</text></view>
        <text v-if="m.from==='me'" class="msg-avatar me">👤</text>
      </view>
    </scroll-view>
    <view class="input-bar"><input v-model="input" class="ib-input" placeholder="输入消息..." @confirm="send"/><view class="ib-send" @click="send">发送</view></view>
  </view>
</template>
<script setup lang="ts">import {ref} from 'vue';import {onPullDownRefresh} from '@dcloudio/uni-app';const group={name:'八字学习群',members:128};const input=ref('');const messages=ref([{id:1,from:'other',user:'周易大师',content:'今天给大家分享八字排盘技巧'},{id:2,from:'other',user:'张玄风',content:'好的老师，期待！'},{id:3,from:'me',content:'准时参加'},{id:4,from:'other',user:'陈风水',content:'已准备好笔记本'}]);function send(){if(!input.value.trim())return;messages.value.push({id:Date.now(),from:'me',user:'我',content:input.value});input.value=''};function goDetail(){uni.navigateTo({url:'/pages/im/group-detail/id-detail/index'})};function goBack(){uni.navigateBack()};onPullDownRefresh(()=>setTimeout(()=>uni.stopPullDownRefresh(),500))</script>
<style scoped>.page{background:#FAF8F5;min-height:100vh;display:flex;flex-direction:column}.nav{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:56px;background:#fff;border-bottom:1px solid #E8E0D5}.nav-back{font-size:36rpx;color:#2C2C2C}.nav-group{display:flex;align-items:center;gap:12rpx}.ng-avatar{width:56rpx;height:56rpx;border-radius:50%;background:rgba(196,30,58,.1);display:flex;align-items:center;justify-content:center;font-size:24rpx;color:#C41E3A}.ng-name{font-size:28rpx;font-weight:500}.ng-count{font-size:22rpx;color:#999}.nav-more{font-size:32rpx;color:#999}.msgs{padding:24rpx;flex:1}.msg{display:flex;gap:12rpx;align-items:flex-start;margin-bottom:24rpx}.msg.right{flex-direction:row-reverse}.msg-avatar{width:56rpx;height:56rpx;border-radius:50%;background:#F5F1EB;display:flex;align-items:center;justify-content:center;font-size:22rpx;color:#2C2C2C;flex-shrink:0}.me-avatar{background:#C41E3A;color:#fff}.msg-body{max-width:70%;padding:16rpx 20rpx;border-radius:16rpx}.msg-body.other{background:#fff;box-shadow:0 2rpx 8rpx rgba(0,0,0,.03)}.msg-body.mine{background:#C41E3A;color:#fff}.mb-user{font-size:22rpx;color:#C41E3A;margin-bottom:6rpx;display:block}.mb-content{font-size:26rpx;line-height:1.5}.input-bar{display:flex;align-items:center;gap:12rpx;padding:16rpx 24rpx;background:#fff;border-top:1px solid #E8E0D5}.ib-input{flex:1;height:72rpx;background:#F5F1EB;border-radius:40rpx;padding:0 24rpx;font-size:26rpx}.ib-send{padding:14rpx 28rpx;background:#C41E3A;color:#fff;border-radius:40rpx;font-size:26rpx}</style>
