<template>
  <view class="page">
    <view class="nav"><text class="nav-back" @click="goBack">←</text><text class="nav-title">回放播放</text><view style="width:48rpx"/></view>
    <view class="video-area"><view class="va-main"><text class="vam-icon">▶</text></view></view>
    <view class="controls"><view class="prog-bar"><view class="pb-track"><view class="pb-fill" :style="{width:progress+'%'}"/><view class="pb-dot" :style="{left:progress+'%'}"/></view></view>
      <view class="ctl-row"><text @click="togglePlay">{{isPlaying?'⏸':'▶'}}</text><text class="ctl-time">{{fmtTime(currentTime)}}/{{fmtTime(duration)}}</text><text class="ctl-speed" @click="cycleSpeed">{{speed}}x</text></view>
    </view>
    <scroll-view scroll-y class="content">
      <view class="info"><text class="info-title">{{replay.title}}</text><view class="info-meta"><text>{{replay.host}}</text><text>👁️{{replay.views}}</text><text>🕐{{replay.duration}}</text></view></view>
      <view class="card"><text class="ct">章节标记</text>
        <view v-for="c in chapters" :key="c.id" class="ch" @click="seek(c.time)"><text class="ch-time">{{fmtTime(c.time)}}</text><text class="ch-title">{{c.title}}</text></view>
      </view>
      <view style="height:48rpx"/>
    </scroll-view>
  </view>
</template>
<script setup lang="ts">import {ref} from 'vue';import {onPullDownRefresh} from '@dcloudio/uni-app';const isPlaying=ref(false),progress=ref(35),currentTime=ref(1200),duration=ref(3600),speed=ref(1);const replay={title:'八字命理入门第一课',host:'周易大师',views:'8,560',duration:'1小时'};const chapters=[{id:1,time:0,title:'开场白'},{id:2,time:300,title:'八字基础概念'},{id:3,time:900,title:'天干地支详解'},{id:4,time:1800,title:'五行生克关系'},{id:5,time:2700,title:'互动问答'}];function fmtTime(s:number){const m=Math.floor(s/60),sec=Math.floor(s%60);return m+':'+(''+sec).padStart(2,'0')};function togglePlay(){isPlaying.value=!isPlaying.value};function cycleSpeed(){const sp=[0.75,1,1.25,1.5,2];const i=sp.indexOf(speed.value);speed.value=sp[(i+1)%sp.length]};function seek(t:number){currentTime.value=t;progress.value=(t/duration.value)*100};function goBack(){uni.navigateBack()};onPullDownRefresh(()=>setTimeout(()=>uni.stopPullDownRefresh(),500))</script>
<style scoped>.page{background:#000;min-height:100vh}.nav{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:48px;background:rgba(0,0,0,.8)}.nav-back{font-size:28rpx;color:#fff}.nav-title{font-size:24rpx;color:#fff}.video-area{padding:12rpx;background:#1a1a2e}.va-main{aspect-ratio:16/9;background:#222;display:flex;align-items:center;justify-content:center;border-radius:8rpx}.vam-icon{font-size:60rpx;color:rgba(255,255,255,.3)}.controls{padding:16rpx 24rpx;background:#000}.prog-bar{position:relative;margin-bottom:16rpx}.pb-track{height:4rpx;background:rgba(255,255,255,.3);border-radius:2rpx}.pb-fill{height:100%;background:#C41E3A;border-radius:2rpx}.pb-dot{position:absolute;top:-6rpx;width:16rpx;height:16rpx;border-radius:50%;background:#C41E3A;margin-left:-8rpx}.ctl-row{display:flex;align-items:center;gap:24rpx;color:#fff;font-size:28rpx}.ctl-time{font-size:20rpx;color:rgba(255,255,255,.6);flex:1}.ctl-speed{font-size:20rpx;padding:4rpx 12rpx;background:rgba(255,255,255,.2);border-radius:8rpx}.content{padding:24rpx;background:#FAF8F5}.info{margin-bottom:20rpx}.info-title{font-size:32rpx;font-weight:600;color:#2C2C2C;display:block}.info-meta{display:flex;gap:24rpx;margin-top:8rpx;font-size:22rpx;color:#999}.card{background:#fff;border-radius:20rpx;padding:24rpx;box-shadow:0 2rpx 12rpx rgba(0,0,0,.04)}.ct{font-size:28rpx;font-weight:600;color:#2C2C2C;margin-bottom:20rpx;display:block}.ch{display:flex;align-items:center;gap:16rpx;padding:16rpx 0;border-bottom:1px solid #F5F1EB}.ch-time{font-size:24rpx;color:#C41E3A;font-weight:500;min-width:80rpx}.ch-title{font-size:24rpx;color:#666}
</style>
