<template>
  <view class="page"><view class="nav"><text class="nb" @click="goBack">←</text><text class="nt">{{u.name}}</text><text class="ns">⋯</text></view>
    <view class="header"><text class="ha">{{u.name[0]}}</text><text class="hn">{{u.name}}</text><text class="hb">{{u.bio}}</text><view class="hs"><text>{{u.following}}关注</text><text>{{u.followers}}粉丝</text></view><view class="hb-btn" @click="toggleFollow">{{u.isfollow?'已关注':'＋关注'}}</view></view>
    <view class="tb"><text v-for="t in tabs" :key="t" class="t" :class="{a:tab===t}" @click="tab=t">{{t}}</text></view>
    <view class="c"><text v-for="p in posts" :key="p.id" class="p">{{p.c}}</text></view></view>
</template>
<script setup lang="ts">import {ref} from 'vue';const tab=ref('动态');const tabs=['动态','帖子','收藏'];const u=ref({name:'周易大师',bio:'资深命理师',following:128,followers:12580,isfollow:false});const posts=ref([{id:1,c:'今天分享一个八字看财运的心得。'},{id:2,c:'食神制杀格局详解。'}]);function toggleFollow(){u.value.isfollow=!u.value.isfollow};function goBack(){uni.navigateBack()}</script>
<style scoped>.page{background:#FAF8F5;min-height:100vh}.nav{display:flex;align-items:center;justify-content:space-between;padding:0 24rpx;height:56px;background:#fff;border-bottom:1px solid #E8E0D5}.nb{font-size:36rpx;color:#2C2C2C}.nt{font-size:32rpx;font-weight:600}.ns{font-size:32rpx;color:#999}.header{text-align:center;padding:40rpx;background:#fff;margin-bottom:16rpx}.ha{width:120rpx;height:120rpx;border-radius:50%;background:rgba(196,30,58,.1);display:flex;align-items:center;justify-content:center;font-size:48rpx;color:#C41E3A;margin:0 auto 16rpx}.hn{font-size:34rpx;font-weight:600;color:#2C2C2C;display:block}.hb{font-size:24rpx;color:#999;margin:8rpx 0 16rpx}.hs{display:flex;justify-content:center;gap:40rpx;font-size:26rpx;color:#2C2C2C;margin-bottom:20rpx}.hb-btn{padding:16rpx 56rpx;background:#C41E3A;color:#fff;border-radius:40rpx;display:inline-block;font-size:26rpx}.tb{display:flex;gap:32rpx;padding:16rpx 24rpx;background:#FAF8F5;border-bottom:1px solid #E8E0D5}.t{font-size:24rpx;color:#999;position:relative}.t.a{color:#C41E3A;font-weight:500}.c{padding:24rpx}.p{background:#fff;border-radius:12rpx;padding:24rpx;margin-bottom:12rpx;font-size:26rpx;color:#2C2C2C}
</style>
